### ISSUE TITLE
Line 49 of MainActivity

### ISSUE THREAD

**Issue by Nardone** [google-developer-training/android-kotlin-fundamentals-apps#1]
https://github.com/google-developer-training/android-kotlin-fundamentals-apps/blob/8805e373964f4bb07638fcb0f3aec438d6c31de4/DiceRoller/app/src/main/java/com/example/android/diceroller/MainActivity.kt#L49
Asking for forgiveness for my ignorance, but line 49 should be val randomInt = Random.nextInt (6) +1, that is without the parentheses after the word Random, otherwise to me it signals the error "cannot create an instance of an abstract class "

**Comment by huangyanxiong01** [comment]
@Nardone I have solved this problem and submitted a merge request.
```
val randomInt = Random.nextInt(0, 6)
```

**Comment by realrufans** [comment]
@huangyanxiong01 
```val randomInt = Random.nextInt(0, 6)``` prints Int numbers from 0 Untill 5 and won't print 6. The tutorial says  its to print from 1 to 6  which was why they did +1  ```val randomInt = Random().nextInt(6) + 1```

I used val randomInt = Random.nextInt(0, 7) instead.

**Comment by jtavva** [comment]
Thank you for your feedback. This issue is addressed and fixed in the pull request,  https://github.com/google-developer-training/android-kotlin-fundamentals-apps/pull/21.
