### ISSUE TITLE
Android Kotlin Fundamentals codelab: 03.3

### ISSUE THREAD

**Issue by rajattri** [google-developer-training/android-kotlin-fundamentals-apps#100]
**Describe the problem**
A clear and concise description of what the problem is.
it is asked to pass argumnets to a method, where it is being called. 
But no information is there in the lecture, on how to edit the method body, where it is defined.
Its possible the lecture is incomplete.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Lesson: 03.3.; Step 2.

**How to reproduce?**
What are the exact steps to reproduce the problem?
No need.

**Versions**
1. What version of Android Studio are you using?
3.6.0

2. What API level are you targeting?
5.0
**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by donatelloraphael** [comment]
Is this the line of code you are talking about?
`                        view.findNavController().navigate(GameFragmentDirections.actionGameFragmentToGameWonFragment(numQuestions, questionIndex))
`
If so, the `actionGameFragmentToGameWonFragment` is defined inside the "Java (generated)" folder inside one of the com.example.android.navigation folders. If pressing alt+Enter above the highlighted error marking on `numQuestions` and `questionIndex`, android studio will ask to add arguments to that function. Selecting it will add the arguments and error messages should disappear.

**Comment by rajattri** [comment]
Yeah sure.
Thanks for the the clarification mate!

**Comment by kkuan2011** [comment]
Thanks for helping, @donatelloraphael !
