### ISSUE TITLE
Android Kotlin Fundamentals codelab: 01.3: Image resources and compatibility

### ISSUE THREAD

**Issue by donatelloraphael** [google-developer-training/android-kotlin-fundamentals-apps#102]
**Describe the problem**
Should be `activity-main.xml` instead of `activity_layout.xml` in step 1.

**In which lesson and step of the codelab can this issue be found?**
01.03, Task 5

**codelab:** android-kotlin-fundamentals

**Comment by donatelloraphael** [comment]
Also in step 4 codelab 01.03, Task 5

**Comment by kkuan2011** [comment]
Duplicate of #114
