### ISSUE TITLE
Score Off By One In GuessTheWord App

### ISSUE THREAD

**Issue by MosDevx** [google-developer-training/android-kotlin-fundamentals-apps#11]
The condition in the onCorrect method prevents final score increment in case of full play through.

https://github.com/google-developer-training/android-kotlin-fundamentals-apps/blob/ae7d3ef090c3b13bbaceb736c94e3093db90daf5/GuessTheWordDataBinding/app/src/main/java/com/example/android/guesstheword/screens/game/GameViewModel.kt#L102-L107

**Comment by jtavva** [comment]
Thank you fo your feedback, this issue is fixed in https://github.com/google-developer-training/android-kotlin-fundamentals-apps/pull/20 pull request.
