### ISSUE TITLE
1.3 Typo in activity layout name, should be activity_main.xml

### ISSUE THREAD

**Issue by max-dau** [google-developer-training/android-kotlin-fundamentals-apps#114]
**Describe the problem**
"activity_main.xml" is called "activity_layout.xml"

**In which lesson and step of the codelab can this issue be found?**
01.3 step 5

**How to reproduce?**
none

**Versions**
not relevant

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Per donatelloraphael in other bug report: This is also in step 4 codelab 01.03, Task 5
