### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by max-dau** [google-developer-training/android-kotlin-fundamentals-apps#115]
**Describe the problem**
activity_main.xml is called main_activity.xml

**In which lesson and step of the codelab can this issue be found?**
01.3 6 step 3 4.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Fixed now
