### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ziakhalid** [google-developer-training/android-kotlin-fundamentals-apps#116]
![image](https://user-images.githubusercontent.com/6457710/79644756-97a2b600-81dd-11ea-9349-4c230b8e5d58.png)
https://codelabs.developers.google.com/codelabs/kotlin-android-training-repository/index.html?index=..%2F..android-kotlin-fundamentals#2

Hear it says "Make sure airplane mode is **off** in your device or emulator"  but actually it should be "Make sure airplane mode is **ON** in your device or emulator"  to get the desired result.

**Comment by kkuan2011** [comment]
Fixed now
