### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by levt14** [google-developer-training/android-kotlin-fundamentals-apps#117]
In Homework section, 2 questions: 
1. Where is the right  answers for the questions?
2. Where do I need to submit my app for grading ?

**Comment by kkuan2011** [comment]
Hello, homework questions are optional for you to do on your own and the solutions are not provided. But you can look back at the codelab content to find the answer. There is no submission process for your app, but you could get a code review from a peer!
