### ISSUE TITLE
3.2 Update navigation project dependencies

### ISSUE THREAD

**Issue by chaoszcat** [google-developer-training/android-kotlin-fundamentals-apps#118]
**Describe the problem**
The two implementations in the documentation cannot be used. Android studio complains

    ERROR: Failed to resolve: android.arch.navigation:navigation-fragment-ktx:2.2.2

**In which lesson and step of the codelab can this issue be found?**
[03.2, Step 3](https://codelabs.developers.google.com/codelabs/kotlin-android-training-add-navigation/index.html#2
) (Task: Add navigation components to the project)

**How to reproduce?**
Copy the two dependency implementations into module, and sync. Android studio will not build. The correct implementations that let me build is:

    dependencies {
      ...
      implementation "androidx.navigation:navigation-fragment-ktx:$navigationVersion"
      implementation "androidx.navigation:navigation-ui-ktx:$navigationVersion"
      ...
    }

**Versions**
Android Studio v3.6.2, SDK version 28

**codelab:** android-kotlin-fundamentals

**Comment by Pluu** [comment]
I recommend this opinion.
CodeLab's navigation definition is an old version.

Currently, AndroidX Navigation guides you like this.

https://developer.android.com/jetpack/androidx/releases/navigation

```
dependencies {
  def nav_version = "2.3.0-beta01"

  // Java language implementation
  implementation "androidx.navigation:navigation-fragment:$nav_version"
  implementation "androidx.navigation:navigation-ui:$nav_version"

  // Kotlin
  implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
  implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

  // Dynamic Feature Module Support
  implementation "androidx.navigation:navigation-dynamic-features-fragment:$nav_version"

  // Testing Navigation
  androidTestImplementation "androidx.navigation:navigation-testing:$nav_version"
}
```
