### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Rob192** [google-developer-training/android-kotlin-fundamentals-apps#127]
**Describe the problem**
ViewModelProviders is deprecated

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number: 05.01, step 5

**How to reproduce?**
What are the exact steps to reproduce the problem? run the code as described

to fix it :

        viewModel = ViewModelProvider(this).get(GameViewModel::class.java)

**Comment by GeneAndGoogle** [comment]
Duplicate of #29
