### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by waichee723** [google-developer-training/android-kotlin-fundamentals-apps#135]
**Describe the problem**
Step 2 text should be a header.

**In which lesson and step of the codelab can this issue be found?**
Lesson 7.2, step 2.

**How to reproduce?**
n/a

**Versions**
1. What version of Android Studio are you using?
n/a
2. What API level are you targeting?
n/a

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment]
Thanks. Hard to find in the source doc...it was formatted like a header, but wasn't.
