### ISSUE TITLE
Why not use coroutine.?

### ISSUE THREAD

**Issue by ardakazanci** [google-developer-training/android-kotlin-fundamentals-apps#14]
https://github.com/google-developer-training/android-kotlin-fundamentals-apps/blob/ae7d3ef090c3b13bbaceb736c94e3093db90daf5/TrackMySleepQualityCoroutines/app/src/main/java/com/example/android/trackmysleepquality/sleeptracker/SleepTrackerViewModel.kt#L44

We take all the data in the database but Dispatchers are not used.

**Comment by sleez007** [comment]
LiveData is lifecycle aware and also thread safe so we don't need to  do this within a coroutine scope

**Comment by ardakazanci** [comment]
Thank you for your answer.

But wouldn't it make sense to use Dispatcher.IO when querying the database?

That's exactly the question I had in mind. We get data from the database and we show it.

**Comment by sleez007** [comment]
well u can actually do that, but the take away here is that in your dao , getAllNights returns a livedata that is technically why this was not done in a coroutine scope. let say u change the return type from LiveData<List<EntityClass>> to List<EntityClass> then if u try doing this outside a coroutine scope. room knows it is been queried on the main thread and throws an exception. The idea in summary is if you are to return a livedata from room, then u need not worry about threading any other operation has to be done within a coroutine scope or using any other threading solution. i hope this helps

**Comment by ardakazanci** [comment]
Thank you so much @sleez007

**Comment by sleez007** [comment]
my pleasure
