### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by fudeel** [google-developer-training/android-kotlin-fundamentals-apps#141]
**Describe the problem**
In the first step of "3. Task: Explore the starter app project" (located in the Android Kotlin Fundamentals 03.1: Create a fragment ) you ask the user to download the AndroidTrivia base project. But this is not possibile since you can download the entire repository instead of that little appllicatoin. Can you provide a correct url to pull the AndroidTrivia project?

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
03.1
**How to reproduce?**
What are the exact steps to reproduce the problem?
Just navigate to the 03.1  (Android Kotlin Fundamentals 03.1: Create a fragment) > 3. Task: Explore the starter app project > first step when you ask to download the base project. 

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Hello! You can download the entire repo and then in Android Studio, under File > Open > Navigate to AndroidTrivia project folder. Hope this helps, if you still have an issue, you can reopen a new ticket. Thanks!
