### ISSUE TITLE
2.3 ConstraintLayout - Update Button layout_marginEnd to @dimen/margin_wide instead of 16dp

### ISSUE THREAD

**Issue by michaelyatco** [google-developer-training/android-kotlin-fundamentals-apps#146]
**Describe the problem**
**Invalid value for changing the vertical bias of a Button in instructions.**
"Change the vertical bias of the yellow_button to **100**, to drop down the buttons to the bottom of the layout." Should be **1.0**. 

**In which lesson and step of the codelab can this issue be found?**
- Android Kotlin Fundamentals 02.3: Constraint layout using the Layout Editor
- Task 11: Add a chain of buttons
- Step 6

**How to reproduce?**
What are the exact steps to reproduce the problem?
- Go to the following URL - https://codelabs.developers.google.com/codelabs/kotlin-android-training-constraint-layout/index.html?index=..%2F..android-kotlin-fundamentals#10
- Go to Step 6

**Versions**
1. What version of Android Studio are you using? **3.6.3**
2. What API level are you targeting? **29**

**Additional information**
Just an editorial note: In the accompanying XML code, for the Green Button, the layout_marginEnd should have a value of "@dimen/margin_wide" for consistency sake with the other margin assignments. Currently it is, android:layout_marginEnd="16dp".

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Thanks, first issue has been fixed. Will leave this open for the second issue to be fixed.
