### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by eugene-ma** [google-developer-training/android-kotlin-fundamentals-apps#147]
**Describe the problem**
ID attribute value is misspelled in a table: "yellow_buttton" (with 3 t's) should be "yellow_button" (with 2 t's).

**In which lesson and step of the codelab can this issue be found?**
2.3.11: Step 1, part 3

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment]
Good catch. Fixed.
