### ISSUE TITLE
Android Kotlin Fundamentals codelab: 02.3: Constraint layout using the Layout Editor

### ISSUE THREAD

**Issue by Gakai** [google-developer-training/android-kotlin-fundamentals-apps#149]
**Describe the problem**
Hovering over a View to display a popup including the wrench not working.
I can't find, where this option went. Please update codelab to include this information.

**In which lesson and step of the codelab can this issue be found?**
Lesson 2.3.10, after Step 1, paragraph "Design-time attributes"

**How to reproduce?**
Install Android Studio 3.6.3
Follow the Codelab.

**Versions**
1. What version of Android Studio are you using?
Android Studio 3.6.3
2. What API level are you targeting?
minSdkVersion 19
targetSdkVersion 29

**Additional information**
Me hovering a TextView. It shows only a bubble containing the View id:
![Hovering](https://user-images.githubusercontent.com/6656683/81346316-628dd300-90ba-11ea-9c0f-51e90ceba38e.PNG)

**codelab:** android-kotlin-fundamentals

**Comment by Gakai** [comment]
![Hovering](https://user-images.githubusercontent.com/6656683/81346053-e4313100-90b9-11ea-8713-04fb94c1e569.PNG)

**Comment by eugene-ma** [comment]
The tutorial seems to be talking about an older version of Android Studio. For the latest version (version 3.6.3), I found that you can just right-click and select "**Set Sample Data**" to get the "**Design-time View Attributes**" menu.
