### ISSUE TITLE
When observe LiveData in Fragment, it is better to use `viewLifecycleOwner`

### ISSUE THREAD

**Issue by takahirom** [google-developer-training/android-kotlin-fundamentals-apps#15]
Because the Fragment lifecycle is longer than the view lifecycle. When back from the back stack, the Fragment view will be leaked.
https://github.com/google-developer-training/android-kotlin-fundamentals-apps/blob/master/GuessTheWordLiveData/app/src/main/java/com/example/android/guesstheword/screens/game/GameFragment.kt#L57

**Comment by jtavva** [comment]
Thank you for your feedback.
This is fixed now in the pull request: https://github.com/google-developer-training/android-kotlin-fundamentals-apps/pull/24
