### ISSUE TITLE
Unresolved Reference: setImageResource() - need more details

### ISSUE THREAD

**Issue by vsvikas08** [google-developer-training/android-kotlin-fundamentals-apps#150]
setImageResource() is not working Android Studio is saying Unresolved Reference: setImageResource()

**Comment by kkuan2011** [comment]
Did you add the dice images to your app and pass in a resource ID to that method call?

Here's the solution code
https://github.com/google-developer-training/android-kotlin-fundamentals-apps/blob/master/DiceRollerFinal/app/src/main/java/com/example/android/diceroller/MainActivity.kt
