### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by gogetron** [google-developer-training/android-kotlin-fundamentals-apps#154]
**Describe the problem**
There is a visual bug in the code in point 3 of the 5th step in kotlin fundamentals 4.2

**In which lesson and step of the codelab can this issue be found?**
Lesson number 4.2+ step number 5, point 3.

**How to reproduce?**
What are the exact steps to reproduce the problem?
![Captura](https://user-images.githubusercontent.com/65114284/81501257-b6293800-92d7-11ea-9466-ad80dd84bbcc.PNG)

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment]
Thanks for the report. Fixed.
