### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by marcodb97** [google-developer-training/android-kotlin-fundamentals-apps#158]
02.1: Linear layout using the Layout Editor
4. Task: Change the root layout to use LinearLayout

<img width="194" alt="Screenshot 2020-05-11 at 21 10 30" src="https://user-images.githubusercontent.com/22169710/81601912-f2d65b80-93cb-11ea-9904-4c1922255497.png">

**Comment by GeneAndGoogle** [comment]
See #49
