### ISSUE TITLE
Android Kotlin Fundamentals codelab: 05.2: LiveData and LiveData observers + Step 8

### ISSUE THREAD

**Issue by KseniaKrasotina** [google-developer-training/android-kotlin-fundamentals-apps#161]
**Describe the problem**
App crashes when gameFinished() is called. 

**In which lesson and step of the codelab can this issue be found?**
05.2: LiveData and LiveData observers + Step 8

**How to reproduce?**
1. Open an app
2. Tap PLAY button
3. Tap END GAME button on the Game Screen

**Versions**
1. What version of Android Studio are you using? 3.6.3
2. What API level are you targeting? 29

**Additional information**
Method threw 'java.lang.NullPointerException' exception. Cannot evaluate com.example.android.guesstheword.screens.game.GameFragmentDirections$ActionGameToScore.toString()

Method threw 'java.lang.NullPointerException' exception. Cannot evaluate com.example.android.guesstheword.screens.game.GameFragmentDirections$ActionGameToScore.toString()

**codelab:** android-kotlin-fundamentals

**Comment by rainpoi** [comment]
I have met the same problem.
I use the "try catch".
`    private fun gameFinished() {
        Toast.makeText(activity, "Game has just finished", Toast.LENGTH_SHORT).show()
        val action = GameFragmentDirections.actionGameToScore()
        action.score = viewModel.score.value?:0
        try{findNavController(this).navigate(action)}
        catch (e:Exception){
            Log.d("exception","exception")
        }
        viewModel.onGameFinishComplete()
    }`
then I find the exception:"kotlin.UninitializedPropertyAccessException: lateinit property viewModel has not been initialized"
at com.example.android.guesstheword.screens.score.ScoreFragment.onCreateView(ScoreFragment.kt:54)

so I change the code from
` **_viewModel.score.observe(viewLifecycleOwner, Observer { newScore ->
            binding.scoreText.text = newScore.toString()
        })_**
        viewModelFactory = ScoreViewModelFactory(ScoreFragmentArgs.fromBundle(arguments!!).score)
        viewModel = ViewModelProvider(this, viewModelFactory)
                .get(ScoreViewModel::class.java)
        viewModel.eventPlayAgain.observe(viewLifecycleOwner, Observer { playAgain ->
            if (playAgain){
                findNavController().navigate(ScoreFragmentDirections.actionRestart())
                viewModel.onPlayAgainComplete()
            }
        })
        binding.playAgainButton.setOnClickListener {
            viewModel.onPlayAgain()
        }
        return binding.root`
To
`        viewModelFactory = ScoreViewModelFactory(ScoreFragmentArgs.fromBundle(arguments!!).score)
        viewModel = ViewModelProvider(this, viewModelFactory)
                .get(ScoreViewModel::class.java)
        viewModel.eventPlayAgain.observe(viewLifecycleOwner, Observer { playAgain ->
            if (playAgain){
                findNavController().navigate(ScoreFragmentDirections.actionRestart())
                viewModel.onPlayAgainComplete()
            }
        })
        **_viewModel.score.observe(viewLifecycleOwner, Observer { newScore ->
            binding.scoreText.text = newScore.toString()
        })_**
        binding.playAgainButton.setOnClickListener {
            viewModel.onPlayAgain()
        }
        return binding.root`
Hope that will help you.
