### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ShubhamYGS** [google-developer-training/android-kotlin-fundamentals-apps#172]
**Describe the problem**
After adding the safe-args plugin to project it started showing the error on all binding views. (eg binding.root)

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 03.3: Start an external activity

**How to reproduce?**
Add the safe-args plugin after adding the binding plugin.

**Versions**
Android Studio Version: 3.5
API Level- 29

**codelab:** android-kotlin-fundamentals

**Comment by ShubhamYGS** [comment]
**Solution**
So, I came up with the solution also. Just do the invalidate cache/restart to solve this problem. 
Please add "Invalidate cache/restart" statement in your codelab. As this issue is faced by many people.

**Comment by kkuan2011** [comment]
Duplicate to #35
