### ISSUE TITLE
3.2 binding.drawerLayout is not resolving - need more details

### ISSUE THREAD

**Issue by CruxMDQ** [google-developer-training/android-kotlin-fundamentals-apps#176]
**Describe the problem**
The “DrawerLayout” object in “binding.drawerLayout” is not resolving

**In which lesson and step of the codelab can this issue be found?**
Kotlin Fundamentals 3.2, step 10

**How to reproduce?**
Just typing the code line in Android Studio 

**Versions**
1. What version of Android Studio are you using? 3.6.3
2. What API level are you targeting? 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Did you add a resourceID of drawerLayout on DrawerLayout in the XML layout?
