### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by aadehe** [google-developer-training/android-kotlin-fundamentals-apps#178]
Unable to Clone and use the  **AndroidTrivia-Starter** code sample in the GitHub link below into my local repository

https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/tree/master/AndroidTrivia-Starter

I do not see the Clone or download button to download the sample codes from GitHub using the link above.

**Comment by kkuan2011** [comment]
Hello! You'll need to download the whole repo of all the starter apps. https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps

Then in Android Studio, go to File > Open > the folder you just downloaded and navigate to the AndroidTrivia project.
