### ISSUE TITLE
Android Kotlin Fundamentals codelab: 05.3: Data binding with ViewModel and LiveData

### ISSUE THREAD

**Issue by RRK1000** [google-developer-training/android-kotlin-fundamentals-apps#182]
Wrong referenced ViewModel in the task to add string formatting with data binding. The code snippet references the `gameViewModel` instead of `scoreViewModel` to update the `score_text` text view.

The error can be found on
- Lesson 5: Architecture components
- Android Kotlin Fundamentals 05.3: Data binding with ViewModel and LiveData
- Task: Add LiveData to data binding
- Step 3, sub-point 3

**Versions**
1. What version of Android Studio are you using? 3.6.3

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. 
In this step you are adding data formatting to the `game_fragment.xml`, so we are referencing `gameViewModel` to update the score.
