### ISSUE TITLE
Android Kotlin Fundamentals codelab: 08.1 Minor issue with incomplete code

### ISSUE THREAD

**Issue by yashovardhan99** [google-developer-training/android-kotlin-fundamentals-apps#187]
**Describe the problem**
Retrofit Codelab has incomplete code in step 6 (point 11 on page).

**In which lesson and step of the codelab can this issue be found?**
Codelab 08.1 Getting Data from the internet Step 6

**How to reproduce?**
At point 11 in step 6 of this codelab, it reads:

> The complete getMarsRealEstateProperties() method now looks like this:
```
private fun getMarsRealEstateProperties() {
   coroutineScope.launch {
       var getPropertiesDeferred = 
          MarsApi.retrofitService.getProperties()
       try {          
           _response.value = 
              "Success: ${listResult.size} Mars properties retrieved"
       } catch (e: Exception) {
           _response.value = "Failure: ${e.message}"
       }
   }
}
```

It is missing the line `var listResult = getPropertiesDeferred.await()` inside the `try{}` block.
The corrected code will be:

```
private fun getMarsRealEstateProperties() {
   coroutineScope.launch {
       var getPropertiesDeferred = 
          MarsApi.retrofitService.getProperties()
       try {          
           var listResult = getPropertiesDeferred.await()
           _response.value = 
              "Success: ${listResult.size} Mars properties retrieved"
       } catch (e: Exception) {
           _response.value = "Failure: ${e.message}"
       }
   }
}
```

**codelab:** android-kotlin-fundamentals 08.1: Getting data from the internet

**Comment by holecekp** [comment]
I have the same problem. I cannot believe that it has been a year and the code has not been corrected yet!!

The current code in the codelab is:
```
           ...
           val listResult = MarsApi.retrofitService.getProperties()
           _response.value = "Success: ${listResult.size} Mars properties retrieved"
           ...
```

This is wrong and the code will not even compile (size is undefined). It should be replaced by:
```
                val listResultDeferred = MarsApi.retrofitService.getProperties()
                val listResult = listResultDeferred.await()
                _response.value = "Success: ${listResult.size} Mars properties retrieved"
```

Thank you, yashovardhan99, for posting the solution to the error there.
