### ISSUE TITLE
3.2 Crash on play button pressed - need more details

### ISSUE THREAD

**Issue by dwilliams427** [google-developer-training/android-kotlin-fundamentals-apps#195]
**Describe the problem**
A clear and concise description of what the problem is.

Upon finishing Task 5, pressing the Play button crashes the app.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin fundamentals Chapter 3.2

**How to reproduce?**
What are the exact steps to reproduce the problem?
Downloaded provided project, followed tasks up to task 5, upon which app crashes when the play button is pressed

**Versions**
1. What version of Android Studio are you using? --> 4.0
2. What API level are you targeting? --> 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Hello, can you provide more information on what the logs say when the crash happens?
https://developer.android.com/studio/debug/am-logcat
