### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by v2deep** [google-developer-training/android-kotlin-fundamentals-apps#203]
**Describe the problem**
Download button not available

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 03.1: Create a fragment
3. Task: Explore the starter app project
    Download the AndroidTrivia-Starter Android Studio project.

**How to reproduce?**
Click on "AndroidTrivia-Starter" link 

**Versions**
1. What version of Android Studio are you using? Android 4.0
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Hello! You'll need to download the whole repo of all the starter apps. https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps

Then in Android Studio, go to File > Open > the folder you just downloaded and navigate to the AndroidTrivia project.
