### ISSUE TITLE
3.2: Define navigation paths - Update options menu method signatures onCreateOptionsMenu() and onOptionsItemsSelected()

### ISSUE THREAD

**Issue by csmcallister** [google-developer-training/android-kotlin-fundamentals-apps#209]
**Describe the problem**
In [items 2 & 3 in step 3 in task 9 of 03.2: Define navigation paths](https://codelabs.developers.google.com/codelabs/kotlin-android-training-add-navigation/index.html#8), the `onCreateOptionsMenu` and `onOptionsItemSelected` methods cause Android Studio to complain with: "'onOptionsItemSelected' overrides nothing". My fix was to make the parameters to these methods non-nullable.

**In which lesson and step of the codelab can this issue be found?**
[items 2 & 3 in step 3 in task 9 of 03.2: Define navigation paths](https://codelabs.developers.google.com/codelabs/kotlin-android-training-add-navigation/index.html#8)

**How to reproduce?**
Assuming you've completed all of the previous steps in the lesson with success, start at item 2 of step 3 in the task by copy-pasting the following method into `TitleFragment.kt`:

```kotlin
override fun onCreateOptionsMenu(menu: Menu?, inflater: MenuInflater?) {
   super.onCreateOptionsMenu(menu, inflater)
   inflater?.inflate(R.menu.options_menu, menu)
}
```

A req squiggly line will appear under `override` with the error message mentioned above.

Removing the `?` from the menu param nixes the error and allows the app to run sucessfully:

```kotlin
override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater?) {
   super.onCreateOptionsMenu(menu, inflater)
   inflater?.inflate(R.menu.options_menu, menu)
}
```

Same occurs for the next step with the `onOptionsItemSelected()` method.

**Versions**
1. What version of Android Studio are you using?
4.0
2. What API level are you targeting?
28

**Additional information**
Really loving the tutorials so far, which is why I wanted to raise this issue ;)

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Fixed
