### ISSUE TITLE
1.2 Anatomy of Basic Android Project - typo in path to strings.xml file

### ISSUE THREAD

**Issue by cynthiasunrise** [google-developer-training/android-kotlin-fundamentals-apps#213]
**Describe the problem**
Wrong path for strings.xml

**In which lesson and step of the codelab can this issue be found?**
Anatomy of Basic Android Project + Step 8

Says:
String resources are contained in the values/res/string.xml file.
Should be:
String resources are contained in the res/values/string.xml file.

**codelab:** android-kotlin-fundamentals

**Comment by sleez007** [comment]
it seems your folder structure is wrong . The hierarchy is res > values > string.xml. you can correct the folder structure from you finder or windows explorer or better still from within android studio project menu. Cheers!

**Comment by cynthiasunrise** [comment]
Yes. The folder is wrong but in the codelab ☺

**Comment by kkuan2011** [comment]
Thanks, yup it's a typo in https://codelabs.developers.google.com/codelabs/kotlin-android-training-app-anatomy/index.html?index=..%2F..android-kotlin-fundamentals#7

**Comment by jtavva** [comment]
@cynthiasunrise 
Thank you for reaching out to us.
This should be fixed now.
