### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by mkmrcodes** [google-developer-training/android-kotlin-fundamentals-apps#216]
**Describe the problem**
Correction required for a phrase.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 02.4: Data-binding basics Step 4
3. In ActivityMain .... should be ---> 3. In MainActivity.kt and in addNickName function

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Fixed now
