### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by gagowa** [google-developer-training/android-kotlin-fundamentals-apps#217]
Hi, 
I'm using the last version of android studio
I can't run the code of the https://codelabs.developers.google.com/codelabs/kotlin-android-training-quality-and-states/#5
The lesson 6 seeams no runable.
Almost i have that prompt error : A problem occurred evaluating project ':app'.

Could you please help me to pass that lesson 6.
My email id is fadila.dev.apps@gmail.com

Thanks in advance

**Comment by kkuan2011** [comment]
Hello, unfortunately we'll need more information to debug this issue. Can you reopen a new issue and provide more details on what error you are running into? Thanks!
