### ISSUE TITLE
Android Kotlin Fundamentals codelab: 01.4: Learn to help yourself

### ISSUE THREAD

**Issue by amberream** [google-developer-training/android-kotlin-fundamentals-apps#219]
**Describe the problem**
This lesson needs to be updated for more recent versions of Android Studio.
In Step 1 you create a new activity from the Basic Activity template.  In newer versions of Android Studio, this is implemented with 2 fragments.  The lesson does not reflect this or explain the NavHostFragment

**In which lesson and step of the codelab can this issue be found?**
01.4: Learn to help yourself Step 1

**How to reproduce?**
Create a new basic activity in a recent version of Androd Studio (I'm using 3.6.3)

**Versions**
1. 3.6.3
2. 29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Duplicate of #107
