### ISSUE TITLE
3.1 Error in Android-Trivia-Starter app - more details needed

### ISSUE THREAD

**Issue by KVSRoyal** [google-developer-training/android-kotlin-fundamentals-apps#220]
**Describe the problem**
1. I can't clone/download only the AndroidTrivia-Starter. I have to download the whole repo it belongs to.
2. When I do download and open AndroidTrivia-Starter, I can run the app right away, but once I try to add a Fragment, everything breaks.

**In which lesson and step of the codelab can this issue be found?**
Lesson 03.1 - Step 4.5.

**How to reproduce?**
Follow the instructions up to the above, and then when you try to gradle sync everything stops working.

**Versions**
1. What version of Android Studio are you using? 4.0
2. What API level are you targeting? 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
#1 is working as intended, so it's easier to download all the starter app code at one time.

As for #2, can you provide a specific error about what you see?
