### ISSUE TITLE
Android Kotlin Fundamentals codelab: 02.2: Add user interactivity

### ISSUE THREAD

**Issue by amberream** [google-developer-training/android-kotlin-fundamentals-apps#226]
**Describe the problem**
The text in the nickname TextView is underlined.  Why?  It would be nice for the codelab to address this.  If there are 2 words only the 2nd word is underlined.  There's actually a screenshot in Step 3 that shows this.

**In which lesson and step of the codelab can this issue be found?**
02.2 Step 3

**How to reproduce?**
Type a nickname into the EditText, click done, The EditText is hidden and the TextView shows up with the value but the value is underlined.

**Versions**
1. What version of Android Studio are you using? 4
2. What API level are you targeting? 29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment]
I'm unable to reproduce this with Android Studio 4.0, Build #AI-193.6911.18.40.6514223 and the example text, "Kotlin Fish". I believe it happened (because it's there in the screenshots). What build is your Android Studio, and what text are you entering for the nickname?

**Comment by kkuan2011** [comment]
Since we don't have more information on how to reproduce this, we'll unfortunately have to close for now, but you can reopen a new issue if you still see it!
