### ISSUE TITLE
Android Kotlin Fundamentals codelab: Section 01.2 and 01.3 Titles

### ISSUE THREAD

**Issue by Okarima** [google-developer-training/android-kotlin-fundamentals-apps#229]
**Describe the problem**
The landing page no longer presents all the sections in order. Lessons number 01.2 and 01.3 no longer have their numbers and have been shifted towards the bottom when sorted alphabetically.

**In which lesson and step of the codelab can this issue be found?**
Lesson number 01.2 and 01.3

**How to reproduce?**
Going to the landing page ([https://codelabs.developers.google.com/android-kotlin-fundamentals/](https://codelabs.developers.google.com/android-kotlin-fundamentals/)) and looking for 01.2 or 01.3.

**Versions**
N/A

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment]
Thanks--fixed. It may take a while for the update to appear on https://codelabs.developers.google.com/android-kotlin-fundamentals/

**Comment by GeneAndGoogle** [comment]
The lesson numbers are being removed. It may take a while for all the lessons to be republished and the landing page updated.
