### ISSUE TITLE
3.2 Define Navigation paths - App bar title is wrong

### ISSUE THREAD

**Issue by amberream** [google-developer-training/android-kotlin-fundamentals-apps#231]
**Describe the problem**
The title in the app bar displays the wrong value after completing this lesson.  Previously the app bar would show "Android Trivia" in the app bar. After completing this lesson, the title fragment and the game won/over fragments show the fragment name in the app bar rather than "Android Trivia".  Would be nice if the lesson addressed why this is happening and how to fix this.

**In which lesson and step of the codelab can this issue be found?**
Lesson 3.2

**How to reproduce?**
Complete the lesson, run the app, and notice the title displayed in the app bar for the title screen and the final screens (game won/over)

**Versions**
1. What version of Android Studio are you using? 4
2. What API level are you targeting? 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kamalx** [comment]
I encountered the same problem. Found that the `label` for those two fragments was set to the default string of fragment name which I missed changing when they were added.

example image:
![image](https://user-images.githubusercontent.com/94972/91230669-8cdacd80-e749-11ea-8141-1237b8daf924.png)

I needed to set the `label` for both `gameWonFragment` and `gameOverFragement` and the next build fixed it for me.

Hope this helps.
