### ISSUE TITLE
Android Kotlin Fundamentals codelab: 3.3 Start an external activity

### ISSUE THREAD

**Issue by amberream** [google-developer-training/android-kotlin-fundamentals-apps#232]
**Describe the problem**
In step 2 we add the navigation-safe-args-gradle-plugin.  It show the dependency as:
   "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
But this gives an error: Could not find android.arch.navigation:navigation-safe-args-gradle-plugin:2.3.0.
The correct dependency is:
    "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

**In which lesson and step of the codelab can this issue be found?**
3.3 Step 2

**How to reproduce?**
Follow Lesson 3.3 Step 2

**Versions**
1. What version of Android Studio are you using? 4
2. What API level are you targeting? 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by nikhilsutar123** [comment]
hey @amberream did you face this issue: `val args = GameWonFragmentArgs.fromBundle(arguments)` in GameWonFragment.kt shows unresolved reference: GameWonFragmentArgs

**Comment by nikhilsutar123** [comment]
Nevermind @amberream. I fixed it by rebuilding it.

**Comment by kkuan2011** [comment]
Duplicate to #35
