### ISSUE TITLE
Android Kotlin Fundamentals codelab: 03.2 | variable view not defined

### ISSUE THREAD

**Issue by V1shvesh** [google-developer-training/android-kotlin-fundamentals-apps#237]
**Describe the problem**
`view` is not defined in the `onOptionsItemSelected` function.

**In which lesson and step of the codelab can this issue be found?**
Lesson 03.2, Step 3.3 

**How to reproduce?**
Copy the step as it is.

**Versions**
1. What version of Android Studio are you using? Android Studio 4.0
2. What API level are you targeting? 28

**Additional information**
```kotlin
override fun onOptionsItemSelected(item: MenuItem?): Boolean {
   return NavigationUI.onNavDestinationSelected(item!!,
           view!!.findNavController())
           || super.onOptionsItemSelected(item)
}
```

**codelab:** android-kotlin-fundamentals

**Comment by anantcodes** [comment]
override fun onOptionsItemSelected(item: MenuItem?): Boolean {
   return NavigationUI.onNavDestinationSelected(item!!,
           NavHostFragment.findNavController())
           || super.onOptionsItemSelected(item)
}

**Comment by V1shvesh** [comment]
Yup, should update the codelab accordingly
.
