### ISSUE TITLE
Android Kotlin Fundamentals codelabs landing page lesson listing issue

### ISSUE THREAD

**Issue by qobilidop** [google-developer-training/android-kotlin-fundamentals-apps#239]
**Describe the problem**
The problem is not about the course content, but about the [Android Kotlin Fundamentals codelabs landing page](https://codelabs.developers.google.com/android-kotlin-fundamentals/). There are 2 lessons with inconsistent naming:

- Android Kotlin Fundamentals: Anatomy of Basic Android Project
- Android Kotlin Fundamentals: Image resources and compatibility

They are lesson 01.2 and 01.3 respectively, but somehow missing the lesson number in their titles. I suggest rename them to make the listing easier to browse.

**Comment by kkuan2011** [comment]
Duplicate of #277
