### ISSUE TITLE
2.4: Data-binding basics - typo in findViewById()

### ISSUE THREAD

**Issue by shazomii** [google-developer-training/android-kotlin-fundamentals-apps#252]
In task two of the lesson: Data-binding basics, the first item of the list stating the benefits of data binding erroneously refers to `findByView()` instead of `findViewById()`.

**Codelab:** 02.4: Data-binding basics

**Comment by jtavva** [comment]
@shazomii 
Thank you for reaching out to us.
This should be fixed now.
