### ISSUE TITLE
GuessTheWord, Lesson 5 :GameViewModel updateScoreText and updateWordText

### ISSUE THREAD

**Issue by 2000Vlad** [google-developer-training/android-kotlin-fundamentals-apps#255]
updateScoreText and updateWordText are defined inside GameFragment and cannot be accessed from GameViewModel, altough the solution code does build successfully, the codelab instructions are not following it.

**Comment by anotheraccountusername** [comment]
All references to updateWordText() and updateScoreText() should be removed at the end of step 6.
5.1, Task 6, Step 1: 
![image](https://user-images.githubusercontent.com/69217024/89350924-f00f9d80-d67e-11ea-870e-4ca74c216338.png)
