### ISSUE TITLE
8.2 url does not load into the textview when you use the @JSON tag

### ISSUE THREAD

**Issue by EricTGoto** [google-developer-training/android-kotlin-fundamentals-apps#258]
**Describe the problem**
A clear and concise description of what the problem is.
The url does not load into the textview when you use the @Json tag. When you remove it and just leave the object as val img_src: String it will display.
**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
08.1 step 5
**How to reproduce?**
Just follow instructions
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by EricTGoto** [comment]
Solution is to remove the @Json tag

**Comment by TheCodingArcher** [comment]
Yes. Its working after removing the Json tag.
Also remove the Moshi dependency as it does not do anything good.
Best is to use GsonConverterFactory.

**PS - @EricTGoto please close this issue as it is resolved**.
