### ISSUE TITLE
01.2 basic app anatomy remarks

### ISSUE THREAD

**Issue by jderijke** [google-developer-training/android-kotlin-fundamentals-apps#26]
Proposed changes

- task 4, Step 5 second bullet:

from: The setOnClick**Handler**() method, which connects the Button to the handler method.
to;     The setOnClick**Listener**() method, which connects the Button 
to the handler method.

- task 5, step 2, end of first paragraph

from: The task of generating a random number isn't Android-specific, and you use the Random class to do it. 
to;    The task of generating a random number isn't Android-specific, and you use the random() function on the range to do it. 

Thanks a lot for the great course!
Hope this is the correct location to provide feedback (the course does not give a pointer to an appropriate feedback  location)
Keep up the good work!

**Comment by jtavva** [comment]
This is fixed now. Thank you for your feedback.
