### ISSUE TITLE
9.1: Repository - typo in codelab

### ISSUE THREAD

**Issue by theankitbhardwaj** [google-developer-training/android-kotlin-fundamentals-apps#260]
In tutorial.
In _Point 1_ (In database/Room.kt, define a VideoDao interface and annotate _**is**_ with @ Dao.) of _Step 3 (Add VideoDao)_ of 
_Task 5 (Add an offline cache)_:

Correction: **_is_** must be replaced with **_it_**

**Comment by kkuan2011** [comment]
https://codelabs.developers.google.com/codelabs/kotlin-android-training-repository/index.html?index=..%2F..android-kotlin-fundamentals#4
