### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ictwill** [google-developer-training/android-kotlin-fundamentals-apps#268]
**Describe the problem**
ViewModelProviders.of() is DEPRECATED

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
5.1 Android Kotlin Fundamentals 05.1: ViewModel and ViewModelFactory
step 5

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Duplicate of #33
