### ISSUE TITLE
01.4 Learn to help yourself: no snackbar

### ISSUE THREAD

**Issue by jderijke** [google-developer-training/android-kotlin-fundamentals-apps#27]
Maybe I missed something but starting from the Basic Activity template in studio 3.5.3 i do not find a Snackbar in the generated activity.

**Comment by avez321** [comment]
`@NonNull
        public Builder<T> setQueryExecutor(@NonNull Executor executor) {
            mQueryExecutor = executor;
            return this;
        }`

**Comment by jtavva** [comment]
Thank you for reaching out to us. We just verified the code generated for basic activity template in the Android Studio stable version 3.5.3. Snackbar code is generated in the `onCreate()` method, inside `setOnClickListener` callback.


~~~
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        setSupportActionBar(toolbar)

        fab.setOnClickListener { view ->
            Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                .setAction("Action", null).show()
        }
    }
~~~

**Comment by jderijke** [comment]
retested, you are right, my bad
