### ISSUE TITLE
1.1 Getting Started - Virtual device not available for Android 4.4

### ISSUE THREAD

**Issue by amukherjee** [google-developer-training/android-kotlin-fundamentals-apps#270]
**Describe the problem**
Package is unavailable 

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 01.1: Get started + Step 6 

**How to reproduce?**
trying to download Virtual device for Android 4.4 

**Versions**
1. Android Studio version 4.0.1
2. What API level are you targeting?

**Additional information**
Virtual Device is not available :
- Package id system-images;andorid-19;armeabi-v7a
**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Can you try creating a virtual device for Android 10 instead?
