### ISSUE TITLE
2.4 Error in data binding variable of type com.example.android.aboutme.MyName

### ISSUE THREAD

**Issue by sanjac0002** [google-developer-training/android-kotlin-fundamentals-apps#275]
**Describe the problem**
The code mentioned gives an
 `<variable
       name="myName"
       type="com.example.android.aboutme.MyName" />`

Here .android creates an error

**In which lesson and step of the codelab can this issue be found?**
Lesson number 2.4.4 + step number 2

**Versions**
1. What version of Android Studio are you using?
3.6

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
What is the package name of your app? Is it com.example.android.aboutme?

**Comment by sanjac0002** [comment]
It is " com.example.aboutme". I apologize for the mistake , I did not see it through!
