### ISSUE TITLE
Numbering is missing for some codelabs (like Data Binding Basics codelab)

### ISSUE THREAD

**Issue by gnurlbash** [google-developer-training/android-kotlin-fundamentals-apps#277]
The Android Kotlin Fundamentals codelabs landing page (https://codelabs.developers.google.com/android-kotlin-fundamentals/) doesn't feature the 2.4 Data Binding basics codelab (https://codelabs.developers.google.com/codelabs/kotlin-android-training-data-binding-basics/index.html#0)

**Comment by kkuan2011** [comment]
Fixed now! 
https://codelabs.developers.google.com/android-kotlin-fundamentals/
