### ISSUE TITLE
Android Kotlin Fundamentals codelab: highlight mistakes

### ISSUE THREAD

**Issue by erikagioka** [google-developer-training/android-kotlin-fundamentals-apps#28]
**Describe the problem**
The position of the code highlight seems to be slightly different.

[Wrong]
`findViewById<Button>(R.id.done_button) ⇒ binding.doneBu`tton

[Correct]
`findViewById<Button>(R.id.done_button) ⇒ binding.doneButton`

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 02.4: Data-binding basics
6. Summary

Thank you.

**Comment by GeneAndGoogle** [comment]
Thanks for catching this. It seems to be a quirk of the codelab tool, so I change the highlighting to break it into two:
`findViewById<Button>(R.id.done_button)` ⇒ `binding.doneButton`
