### ISSUE TITLE
Android Kotlin Fundamentals codelab: There is a small typo in the directions versus the example code 

### ISSUE THREAD

**Issue by aboddenp** [google-developer-training/android-kotlin-fundamentals-apps#290]
There is a small typo in the directions versus the example code: The directions says to put GridLayout.Vertical but the actual snippet uses the GridLayout.Horizontal

**Where?** 
--Lesson 7.3 + task 4 step 2.8

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Duplicate of #41
