### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by plmokn080** [google-developer-training/android-kotlin-fundamentals-apps#296]
**Describe the problem**
A clear and concise description of what the problem is.
I have finished the tutorial and follow every step. However, there is no response after I press the "play" button when questions should appear

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
0.3.1 + 4
**How to reproduce?**
What are the exact steps to reproduce the problem?
I follow every step 
**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?
  gradleVersion = '4.0.0'
**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Hello, we actually need more information to debug this issue so will have to close this for now. You can reopen a new ticket and provide more details on how to reproduce the issue. Another thing to try is to look at the solution code for this codelab: https://github.com/google-developer-training/android-kotlin-fundamentals-apps
