### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by akhileshdhar** [google-developer-training/android-kotlin-fundamentals-apps#298]
**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

FOR questions  answers: Answer is not selectable.

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Hello! The questions are provided as supplementary material but not intended to be interactive in this codelab. In newer courses, we do have interactive quizzes with badges though: https://developer.android.com/courses/android-basics-kotlin/course
