### ISSUE TITLE
Android Kotlin Fundamentals codelab: 05.2: variable name inside `onCorrect` function

### ISSUE THREAD

**Issue by ianre657** [google-developer-training/android-kotlin-fundamentals-apps#30]
**Describe the problem**

The variable name of the sample code is wrong

```kotlin
fun onCorrect() {
   _score.value = (_score.value)?.plus(1)
   nextWord()
}
```
since we doesn't introduce the encapsulation of `LiveData`  until the section 6 of 05.2, we should use `score` in stead of `_score` as its variable name.

So the correct function should look like this:

```kotlin
fun onCorrect() {
   score.value = (score.value)?.plus(1)
   nextWord()
}
```

**In which lesson and step of the codelab can this issue be found?**
05.2 +Step 2 (2. `fun onCorrect`)

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment]
Thanks for catching this. Fixed.
