### ISSUE TITLE
7.3 Homework question - LinearLayoutManager is misspelled

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#306]
**Describe the problem**
A clear and concise description of what the problem is.
In Question 1 of the "Answer these questions" section of Homework, "LinearLayoutManager" is misspelled as "LinearLayouManager" (missing. "t") -- unless of course this was a trick question :)

**In which lesson and step of the codelab can this issue be found?**
Lesson number Android Kotlin Fundamentals 07.3: GridLayout with RecyclerView + step number 8. Homework.

**How to reproduce?**
What are the exact steps to reproduce the problem?
Misspelling in codelab text

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@ken-brown 
Thank you so much for reporting this issue. This is fixed and will be published soon.
