### ISSUE TITLE
Android Kotlin Fundamentals codelab: missing await() call causes compiler error

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#314]
**Describe the problem**
A clear and concise description of what the problem is.
In this lesson there are instructions to replace try/catch code in getMarsRealEstateProperties() method with the following:
`try {
    **_properties.value = MarsApi.retrofitService.getProperties()**   
    _response.value = "Success: Mars properties retrieved"
} catch (e: Exception) {
   _response.value = "Failure: ${e.message}"
}
 `
However, this will result in the following compile time error:
`Type mismatch: Inferred type is Deferred<List<MarsProperty>> but List<MarsProperty>? was expected`

**In which lesson and step of the codelab can this issue be found?**
Lesson number  08.2 Android Kotlin Fundamentals: Loading and displaying images from the internet + step number 4. Task: Display a grid of images with a RecyclerView.

**How to reproduce?**
What are the exact steps to reproduce the problem?
Follow the instructions in the codelab, specifically in Step 1: Update the view model, numbered statement 4.

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 28

**Additional information**
It is missing a call to await() on the Deferred object when setting _properties.value.  This line fixes it:
`_properties.value = MarsApi.retrofitService.getProperties().await()`

**codelab:** android-kotlin-fundamentals

**Comment by ken-brown** [comment]
This missing await() also occurs in Task 5, Step 1: Add status to the view model, numbered statement 4 in the code.

**Comment by jtavva** [comment]
@ken-brown 
Thank you for reaching out to us.
This should be fixed now. If not, you can always reopen this issue or raise a new one if you need any further assistance.
