### ISSUE TITLE
Android Kotlin Fundamentals codelab: Typos

### ISSUE THREAD

**Issue by jdelliot** [google-developer-training/android-kotlin-fundamentals-apps#315]
**Describe the problem**
`Dispatchers.xxx` is spelled wrong twice on the same page.

**In which lesson and step of the codelab can this issue be found?**
06.2 step 8, second section. Should be `Dispatchers.Main` and later `Dispatchers.IO`

**How to reproduce?**
Land on page, read text.

**Versions**
1. What version of Android Studio are you using? N/A
2. What API level are you targeting? N/A

**Additional information**
N/A

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@jdelliot 
Thank you so much for reporting this issue. This is fixed and will be published soon.
