### ISSUE TITLE
Android Kotlin Fundamentals codelab: "Android Kotlin Fundamentals: Getting data from the internet" forgot to import the dependency "androidx.lifecycle:lifecycle-viewmodel-ktx"

### ISSUE THREAD

**Issue by graffiti75** [google-developer-training/android-kotlin-fundamentals-apps#316]
**Describe the problem**
At [this Codelab](https://codelabs.developers.google.com/codelabs/kotlin-android-training-internet-data/index.html?index=..%2F..android-kotlin-fundamentals#5):

```
Android Kotlin Fundamentals: Getting data from the internet
 6. Task: Use coroutines with Retrofit
```

There are no references to this import:

```
// ViewModel
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$version_lifecycle"
```

Without it, the code from this section won't compile.

**In which lesson and step of the codelab can this issue be found?**
Lesson number 08.1 + step number 6.

**How to reproduce?**
The code won't compile in Android Studio. For it to compile, we need to import `import androidx.lifecycle.viewModelScope` for calling the method `viewModelScope.launch` on method `private fun getMarsRealEstateProperties()`.
But where is the reference for this import in this Codelab?

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 28

**Additional information**
No additional informations.

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for filing the issue, this import is present in the starter app. 

// ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$version_lifecycle"

Please refer:
https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/blob/master/MarsRealEstate-Starter/app/build.gradle
