### ISSUE TITLE
Android Kotlin Fundamentals codelab: 05.4: Linked to deprecated source

### ISSUE THREAD

**Issue by ianre657** [google-developer-training/android-kotlin-fundamentals-apps#32]
**Describe the problem**
The document which `Transformations.map()` linked to has been deprecated.
use `anrdoid.x` instead of `android.arch` package

**In which lesson and step of the codelab can this issue be found?**
05.4 task 5, first link 
![Screenshot from 2020-02-11 13-44-24](https://user-images.githubusercontent.com/13212935/74213542-b2841600-4cd4-11ea-83fa-3bf6b4ab90fc.png)

**How to reproduce?**
Just click the url

**Additional information**

Change the URL from [https://developer.android.com/reference/android/arch/lifecycle/Transformations.html#map%28android.arch.lifecycle.LiveData%3CX%3E,%20android.arch.core.util.Function%3CX,%20Y%3E%29](https://developer.android.com/reference/android/arch/lifecycle/Transformations.html#map%28android.arch.lifecycle.LiveData%3CX%3E,%20android.arch.core.util.Function%3CX,%20Y%3E%29)
to 
[https://developer.android.com/reference/androidx/lifecycle/Transformations.html#map(androidx.lifecycle.LiveData%3CX%3E,%20androidx.arch.core.util.Function%3CX,%20Y%3E)](https://developer.android.com/reference/androidx/lifecycle/Transformations.html#map(androidx.lifecycle.LiveData%3CX%3E,%20androidx.arch.core.util.Function%3CX,%20Y%3E))

**codelab:** android-kotlin-fundamentals

**Comment by jwill** [comment]
Fixed as of 12 FEB.
