### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Arman-Kussainov** [google-developer-training/android-kotlin-fundamentals-apps#324]
**Describe the problem**
Misprint in the android project file name in the lesson
you have "Open activity_layout.xml in the Text tab."
but it should be written as "Open activity_main.xml layout in the Text tab."

In which lesson and step of the codelab can this issue be found?
Android Kotlin Fundamentals 01.3: Image resources and compatibility
step 5

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@Arman-Kussainov 
This is fixed now. Thank you for your help.
