### ISSUE TITLE
Android Kotlin Fundamentals codelab:  03.3 - Wrong import in tutorial

### ISSUE THREAD

**Issue by mmaia** [google-developer-training/android-kotlin-fundamentals-apps#326]
**Describe the problem**
safe-args dependency namespace has changed but stil shows old in code

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 03.3: Start an external activity

**How to reproduce?**
Try to import as stated in step 2 -> `classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"`

**Versions**
1. What version of Android Studio are you using?
IntelliJ Idea 2020.2 with Android SDK 9.0 (Pie) API Level 28
Android SDK Tools 26.1.1
Android SDK Platform-Tools 30.0.4

2. What API level are you targeting?
minSdkVersion 19
compileSdkVersion 28

**Additional information**
I have changed to `classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"` ,  and updated the `navigationVersion` to 2.2.2 and it seems to work.

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
