### ISSUE TITLE
Android Kotlin Fundamentals codelab 03.2: 

### ISSUE THREAD

**Issue by elmalakomar** [google-developer-training/android-kotlin-fundamentals-apps#327]
**Describe the problem**
I copied the code available in the codelab reported and Android Studio showed me one error.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 03.2: + 9. Task: Add an options menu

**How to reproduce?**
In Step 3: Add an onClick handler, copying the code 
override fun onOptionsItemSelected(item: MenuItem?): Boolean {
   return NavigationUI.onNavDestinationSelected(item!!,
           view!!.findNavController())
           || super.onOptionsItemSelected(item)
}
You'll have an error on the view!!.
I changed it with requireView()

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
