### ISSUE TITLE
06.2 ViewModelProviders  is deprecated

### ISSUE THREAD

**Issue by ianre657** [google-developer-training/android-kotlin-fundamentals-apps#33]
similar to #29 

**Describe the problem**
The `ViewModelProviders` is deprecated, use `ViewModelProvider` directly.

**In which lesson and step of the codelab can this issue be found?**

06.2 Task 4 and probably every paragraph after that

**Additional information**

Replace every occurrence of

```kotlin
val sleepTrackerViewModel =
       ViewModelProviders.of(
               this, viewModelFactory).get(SleepTrackerViewModel::class.java)
```
to
```kotlin
val sleepTrackerViewModel =
       ViewModelProvider(
               this, viewModelFactory).get(SleepTrackerViewModel::class.java)
```

**codelab:** android-kotlin-fundamentals

**Comment by AayuStark007** [comment]
Hi, Can I submit a PR for fixing this issue?
My changes would be to refactor the code to replace the occurrences of **ViewModelProviders.of()** to **ViewModelProviders()** in the code and include appropriate import statements for the same.

**Comment by amberream** [comment]
The code codelab may have changed since this issue was initially submitted because it's now a charades game rather than a sleep tracker.  I changed the code to this:
```
Log.i("GameFragment", "Called ViewModelProviders.of")
//        viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)
viewModel = ViewModelProvider(this).get(GameViewModel::class.java)
```

**Comment by anotheraccountusername** [comment]
> 
> 
> The code codelab may have changed since this issue was initially submitted because it's now a charades game rather than a sleep tracker. I changed the code to this:
> 
> ```
Actually sleep tracker is in the 6.x codelabs. Anyway your solution will work in both.

**Comment by jtavva** [comment]
fixed
