### ISSUE TITLE
Android Kotlin Fundamentals codelab: 8.2

### ISSUE THREAD

**Issue by kanthi246** [google-developer-training/android-kotlin-fundamentals-apps#330]
**Describe the problem**
In Android Kotlin Fundamentals Loading and displaying images from the internet example when i'm trying to check the size it's showing error(i.e Unresloved reference:size)

**In which lesson and step of the codelab can this issue be found?**
Lesson number:8.2+Task 3+step 2

**Versions**
Android Studio:4.0.1,API level : 29

**codelab:** android-kotlin-fundamentals:8.2

**Comment by jtavva** [comment]
@kanthi246 
Thank you so much for reporting this issue. This is fixed and will be published soon.
