### ISSUE TITLE
Android Kotlin Fundamentals codelab: 5.4 LiveData Transformations

### ISSUE THREAD

**Issue by amberream** [google-developer-training/android-kotlin-fundamentals-apps#332]
**Describe the problem**
Codelab 5.4 Step 2 says, "DateUtils.formatElapsedTime() utility method, which takes a long number of milliseconds and formats it to "MM:SS" string format."

This method actually takes SECONDS, not milliseconds.

**In which lesson and step of the codelab can this issue be found?**
5.4 Step 2

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@amberream 
Thank you so much for reporting this issue. This is fixed and will be published soon.
