### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by pheeya** [google-developer-training/android-kotlin-fundamentals-apps#333]
**Describe the problem**
In the "  if (savedInstanceState != null) {" if block:
The data from the stored state is assigned to variables, but the views are never updated on the front end.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 04.2: Complex lifecycle situations 
couple of final steps are the relevant ones. 

**How to reproduce?**
The problem can easily be reproduced if you just follow along the codelab, you will notice that even though the data is stored in variables, the views are not updated, except for the picture as the showCurrentDessert() function takes care of that.

**Versions**
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 12
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: 

**Additional information**
I think an easy way to fix this problem would be to create a new private restoreState function which takes in the values that needs to be updated and then updates the views using binding.x 
I also put the showCurrentDessert() in the restoreState function to keep things clean.:

    private fun restoreState(rev: Int, sold: Int) {
        binding.revenue = rev;
        binding.amountSold = sold;
        showCurrentDessert();
    }

and then call the function at the end of the "  if (savedInstanceState != null) {"  if block and provide the required parameters! 

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@pheeya This is done through data binding. 
No need to add this code
Thank you for reaching out to us.
