### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by FilipPalusinski** [google-developer-training/android-kotlin-fundamentals-apps#334]
**Describe the problem**
Code for adding safe args to the project is not valid anymore and doesnt work.
classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
According to documentation it should be like this (used androidx):
classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

**In which lesson and step of the codelab can this issue be found?**
03.3 + Step 2

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
 4.0.1
2. What API level are you targeting?
 navigationVersion = '2.3.0'

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
