### ISSUE TITLE
Android Kotlin Fundamentals codelab: 02.4

### ISSUE THREAD

**Issue by Fadel-K** [google-developer-training/android-kotlin-fundamentals-apps#336]
**Describe the problem**
If i update the build.gradle(module:app) by adding 
buildFeatures {
    dataBinding true
}

before the closing braces and try to sync it is showing error "Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method buildFeatures() for arguments [build_3exyqjzs8bk03eiq101zav3gq$_run_closure1$_closure5@4e9bf787] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension."

**In which lesson and step of the codelab can this issue be found?**
02.4r + Step1.

**How to reproduce?**
Given above

**Versions**
1. What version of Android Studio are you using? 28.0.3
2. What API level are you targeting? 30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@Fadel-K 
Thank you for reaching out to us.
You can add buildFeatures() only in Android Studio 4.0+ 
The recommended IDE for this course is latest stable version of Android Studio.
