### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by pkgreen90** [google-developer-training/android-kotlin-fundamentals-apps#337]
**Describe the problem**
When modifying the gradle files you are instructing the person to change the project gradle file based on their previous package they built and modified. However, you have given them the incorrect variable name and the incorrect classpath for the latest 2.3.0 nav-version. The variable should be called "nav_version" and not "navigationVersion based on the code you previously used here: https://codelabs.developers.google.com/codelabs/kotlin-android-training-add-navigation/index.html?index=..%2F..android-kotlin-fundamentals#2

**In which lesson and step of the codelab can this issue be found?**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-start-external-activity/index.html#2
Part 3 step 2. 

Copy the example code you provide and put it into the application based on the previous chapter.
Previous chapter variables:

// Example from the previous chapter
buildscript {
    ext {
...
        supportlibVersion = '1.2.0'
        nav_version = "2.3.0"
        dataBindingCompilerVersion = gradleVersion // Always need to be the same.
    }

// Chapter guidance as is on live training material
// Adding the safe-args dependency to the project Gradle file
dependencies {
   ...
classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
}

// However, it should be as below. 
// This above is using the "android.arch.navigation" path name that does not work anymore. The below works using the newer androidx....
    dependencies {
        classpath "com.android.tools.build:gradle:$gradleVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"

**Versions**
Android Studio: 4.0.1
API Level: 30

**Additional information**
I found this by looking into the navigation support documents here: https://developer.android.com/jetpack/androidx/releases/navigation.

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@pkgreen90 
Thank you for reaching out to us.
This should be fixed now.
