### ISSUE TITLE
Android Kotlin Fundamentals codelab: Spacing in example

### ISSUE THREAD

**Issue by pkgreen90** [google-developer-training/android-kotlin-fundamentals-apps#338]
**Describe the problem**
The spacing using in the example has too much indentation. The excerpt below shows the text from the lesson. The line 
 with 'shareIntent.setType("text/plain")' on has too much indentation. it gives the implications that it is somehow related to the previous line.

// Original excerpt from lesson
<pre>// Creating our Share Intent
private fun getShareIntent() : Intent {  
   val args = GameWonFragmentArgs.fromBundle(arguments!!)  
   val shareIntent = Intent(Intent.ACTION_SEND)  
        shareIntent.setType("text/plain")  
            .putExtra(Intent.EXTRA_TEXT, getString(R.string.share_success_text, args.numCorrect, args.numQuestions))  
   return shareIntent  
}
</pre>

**In which lesson and step of the codelab can this issue be found?**
Lesson 3.3 - Task 5 - Step 2.1 (https://codelabs.developers.google.com/codelabs/kotlin-android-training-start-external-activity/index.html#4)

**How to reproduce?**
Nothing to repoduce.

**Versions**
N/A

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@pkgreen90 
Thank you for reaching out to us.
This should be fixed now.
