### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Hazem0h** [google-developer-training/android-kotlin-fundamentals-apps#339]
**Describe the problem**
A typo:  no such thing as `findByView()`

**In which lesson and step of the codelab can this issue be found?**
Lesson number 02.4 + step number 3.

**How to find it?**
Between the image (which describes data binding) and the heading "Step 1: Enable data binding".
Count 2 lines after the image.
In the second line, you can  see the method is `findByView()` whereas it should be `findViewById()`

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@Hazem0h 
Thank you so much for reporting this issue. This is fixed and will be published soon.
