### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Haffi921** [google-developer-training/android-kotlin-fundamentals-apps#341]
**In which lesson and step of the codelab can this issue be found?**
Lesson 02.4, Task 4, Step 4, Item 3 and 4

**Describe the problem**
I believe there's an error in the text.

In item 3, the text says:

> In MainActivity, replace
> `nicknameText.text = nicknameEdit.text.toString()`
> with code to set the nickname in the myName variable.

The code should be `binding.nicknameText.text = binding.nicknameEdit.text.toString()`

Also, in the code following item 3 it says: `myName?.nickname = nicknameEdit.text.toString()`. The `?` gets flagged for an unnecessary safety call.

In item 4, the text says:

> Add `invalidateAll()` after setting the nickname so that the UI is refreshed with the value in the updated binding object.

The function is `binding.invalidateAll()`. Also check the code below item 4.

**How to reproduce?**
I believe it's an error in the codelab

**Versions**
1. What version of Android Studio are you using?
Using IntelliJ IDEA 2020.2 (Ultimate Edition)
2. What API level are you targeting?
30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@Haffi921 
Thank you for reaching out to us.
Usage of `binding` in the function calls is replaced by the `apply` block, in the following step. 
**3. Task: > Step 4 > numbered step 5. Kotlinize the function by using apply{}.**

```
binding.apply {
   nicknameText.text = nicknameEdit.text.toString()
   nicknameEdit.visibility = View.GONE
   doneButton.visibility = View.GONE
   nicknameText.visibility = View.VISIBLE
}
```
The recommended IDE for this course is stable version of Android Studio. In Android Studio code runs as expected, with out any warnings about the safety call. Hope this helps.
