### ISSUE TITLE
Android Kotlin Fundamentals codelab: "3.3: Start an external activity" Override errors makes compilation impossible

### ISSUE THREAD

**Issue by Osunator** [google-developer-training/android-kotlin-fundamentals-apps#343]
**Describe the problem**
The code given on the override functions calls for "**Menu?**", "**MenuInflater?**" and "**MenuItem?**", that makes the program unable to detect the menu and gives a compilation error saying that is overriding nothing.
You need to remove the "**?**" from all the variables and that makes the code compile correctly.

Also has old code mentioning "**activity!!**" and "**item!!**" instead of "**requireActivity()**" and "**item**"; and the property setVisible should be changed for isVisible.

The code should be:

    override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
        super.onCreateOptionsMenu(menu, inflater)
        inflater.inflate(R.menu.winner_menu, menu)
        if (null == getShareIntent().resolveActivity(requireActivity().packageManager)) {
            menu.findItem(R.id.share)?.isVisible = false
        }
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        when (item.itemId) {
            R.id.share -> shareSuccess()
        }
        return super.onOptionsItemSelected(item)
    }

**In which lesson and step of the codelab can this issue be found?**
On "3.3: Start an external activity" at "5. Task: Add an implicit intent and a "share" menu item" on Step 2 at paragraphs 3 and 4

**How to reproduce?**
Just use the code given and the error won't let you compile

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 14

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
