### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by URJoseG** [google-developer-training/android-kotlin-fundamentals-apps#345]
**Describe the problem**
A clear and concise description of what the problem is.

Following the steps in the codelab will not allow the app to build. 

**In which lesson and step of the codelab can this issue be found?**
03.3: Step 2:

"2. Add the navigation-safe-args-gradle-plugin dependency, as shown below:
// Adding the safe-args dependency to the project Gradle file
dependencies {
   ...
classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

}"

In previous codelabs we defined nav_version instead of navigationVersion
I had to use androidx.navigation instead of android.arch.navigation step 4 applies the plugin for androidx.navigation

**Versions**
1. What version of Android Studio are you using? 4.01
2. What API level are you targeting? 24

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
