### ISSUE TITLE
Android Kotlin Fundamentals codelab: classpath for safe args incorrect

### ISSUE THREAD

**Issue by RavisankarJ** [google-developer-training/android-kotlin-fundamentals-apps#346]
**Describe the problem**
The classpath for safe args in navigation is given as `classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"`. But it shows error when we try to sync. But I think it should be `classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"`

**In which lesson and step of the codelab can this issue be found?**
Lesson number : Android Kotlin Fundamentals 03.3: Start an external activity
step number : 2

**How to reproduce?**
What are the exact steps to reproduce the problem?
Following the steps itself reproduce the problem

**Versions**
1. What version of Android Studio are you using?

> Android Studio 4.0.1
> Build #AI-193.6911.18.40.6626763, built on June 25, 2020
> Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 4.15.0-112-generic
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1246M
> Cores: 4
> Registry: ide.new.welcome.screen.force=true
> Non-Bundled Plugins: org.jetbrains.kotlin, com.google.services.firebase

_
2. What API level are you targeting?

>         minSdkVersion 19
>         targetSdkVersion 30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
