### ISSUE TITLE
Android Kotlin Fundamentals codelab: 03.3

### ISSUE THREAD

**Issue by Bharath20000** [google-developer-training/android-kotlin-fundamentals-apps#349]
dependencies {
   ...
classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

}

adding the above dependecies is not working and returning not found error in,
Android Kotlin Fundamentals 03.3: Start an external activity>Task: Set up and use the Safe Args plugin>step 2>point 2

The error shone is below

Could not find android.arch.navigation:navigation-safe-args-gradle-plugin:2.3.0.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/android/arch/navigation/navigation-safe-args-gradle-plugin/2.3.0/navigation-safe-args-gradle-plugin-2.3.0.pom
  - https://jcenter.bintray.com/android/arch/navigation/navigation-safe-args-gradle-plugin/2.3.0/navigation-safe-args-gradle-plugin-2.3.0.pom

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
