### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by peterterman** [google-developer-training/android-kotlin-fundamentals-apps#354]
Hi
it seems that codelab 5.1 is missing ?

Regards

**Comment by Osunator** [comment]
https://codelabs.developers.google.com/codelabs/kotlin-android-training-view-model/#0

No idea why it doesn't appear with all the others in the list, but it does exists

**Comment by jtavva** [comment]
@peterterman and @Osunator 
Thank you for reaching out to us.
Please use link for reference thank you.
https://developer.android.com/courses/kotlin-android-fundamentals/toc?authuser=1
