### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by DanielGolikov** [google-developer-training/android-kotlin-fundamentals-apps#357]
**Describe the problem**
In the text of the tutorial:
Android Kotlin Fundamentals: Coroutines and Room
Step 3: Display the data
there is information about about definition of UIScope variable, although the new version of the tutorial does not have such a variable
Evidence from text:
Open SleepTrackerViewModel. In the SleepTrackerViewModel class, below the definition of **uiScope**, define a variable called nights. Get all the nights from the database and assign them to the nights variable.

**In which lesson and step of the codelab can this issue be found?**

Android Kotlin Fundamentals: Coroutines and Room
Step 3: Display the data
6. Task: Collect and display the data

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Fixed in the codelab, https://codelabs.developers.google.com/codelabs/kotlin-android-training-coroutines-and-room/#5
