### ISSUE TITLE
Android Kotlin Fundamentals codelab: extraneous "suspend" keyword in lesson 08.3 task 4

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#359]
There is an incorrect addition of the "suspend" keyword infront of 
`suspend fun getProperties(@Query("filter") type: String): List<MarsProperty> `

If the "suspend" is left in place, the code compiles but misbehaves at runtime -- it displays as if there were no internet connectivity by showing the "cloud with diagonal line through it" icon.  

Removing the "suspend" keyword fixes the program execution.

Location of error:
Chapter: 08.3 Android Kotlin Fundamentals: Filtering and detail views with internet data
Task: 4. Task: Filter the results
Step 1: Update the Mars API service
Numbered statement: 2

**Comment by jtavva** [comment]
Thank you for reaching out to us.
We are unable to reproduce this at out end. 
Please re-test after restarting your emulator and Android Studio.
If you are still facing issue please feel free to reach out us.
