### ISSUE TITLE
Android Kotlin Fundamentals codelab: onOptionsItemSelected parameter should be nullable

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#360]
When I autocomplete onOptionsItemSelected function, the "item" parameter is a "MenuItem?".  This is the auto-complete code in Android Studio 4.0.1:
`    override fun onOptionsItemSelected(item: MenuItem?): Boolean {
        return super.onOptionsItemSelected(item)
    }
`
 However, in the text, it is shown without the "?" and the code within the function also assumes it is a non-null object:
`override fun onOptionsItemSelected(item: MenuItem): Boolean {
   viewModel.updateFilter(
           when (item.itemId) {
               R.id.show_rent_menu -> MarsApiFilter.SHOW_RENT
               R.id.show_buy_menu -> MarsApiFilter.SHOW_BUY
               else -> MarsApiFilter.SHOW_ALL
           }
   )
   return true
}`

Location of error:
Chapter 08.3  Android Kotlin Fundamentals: Filtering and detail views with internet data
Task: 4. Task: Filter the results
Step 3: Connect the fragment to the options menu
Numbered statement: 3

**Comment by jtavva** [comment]
@ken-brown 
Thank you for reaching out to us.
Does the code in the codelab and solution code on Github match?
If they do not please feel free to re-open this issue.
