### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by GrigorAmBC** [google-developer-training/android-kotlin-fundamentals-apps#362]
**Describe the problem**
Retrofit of 2.5.0 version doesn't work with Kotlin coroutines meaning that we can't mark, for example, @GET function with suspend keyword in Kotlin. Solution is to switch from 2.5.0 to 2.6.0. The error that I get is "No Retrofit annotation found. (parameter #1)".

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Lesson number is 8.2 "Loading and displaying images from the internet" and step number is 4.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
4.0.1
2. What API level are you targeting?
API level 30
**Additional information**
Here is a link to the description of the error and some solutions:
https://stackoverflow.com/questions/28371305/no-retrofit-annotation-found-parameter-1

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
Retrofit version is updated to 2.9.0
