### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by jmanuel34** [google-developer-training/android-kotlin-fundamentals-apps#366]
**Describe the problem**
There are a mistake in the point 8 of Android Kotlin Fundamentals 02.3: Constraint layout using the Layout Editor

**In which lesson and step of the codelab can this issue be found?**
0.23 + 8.

**How to reproduce?**
Following exactly the lessons.
There are a mistake in the name of the TextView boxes.
The list of views should be:

 val clickableViews: List<View> =
            listOf(box_one_text, box_two_text, box_three_text,
                box_four_text, box_five_text, constraint_layout)
        for (item in clickableViews) {
            item.setOnClickListener { makeColored(it) }

**Versions**
1. What version of Android Studio are you using?
4.0.1
2. What API level are you targeting?
4.4 KitKAT
**Additional information**
The final function should left as follow:

    private fun makeColored(view: View) {
        when (view.id) {
            R.id.box_one_text -> view.setBackgroundColor(Color.DKGRAY)
            R.id.box_two_text -> view.setBackgroundColor(Color. GRAY)
            R.id.box_three_text ->view.setBackgroundColor(Color.BLUE)
            R.id.box_four_text -> view.setBackgroundColor(Color.MAGENTA)
            R.id.box_five_text -> view.setBackgroundColor(Color.BLUE)
            else -> view.setBackgroundColor(Color.LTGRAY)

        }
        val clickableViews: List<View> =
            listOf(box_one_text, box_two_text, box_three_text,
                box_four_text, box_five_text, constraint_layout)
        for (item in clickableViews) {
            item.setOnClickListener { makeColored(it) }
        }

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
There is the no mistake in the function. It is correct! Databinding is not introduced to the students in this codelab.
box_one_text, box_two_text, box_three_text,box_four_text, box_five_text are the variables that are defined in the function. 


```
private fun setListeners() {

        val boxOneText = findViewById<TextView>(R.id.box_one_text)
        val boxTwoText = findViewById<TextView>(R.id.box_two_text)
        val boxThreeText = findViewById<TextView>(R.id.box_three_text)
        val boxFourText = findViewById<TextView>(R.id.box_four_text)
        val boxFiveText = findViewById<TextView>(R.id.box_five_text)

        val rootConstraintLayout = findViewById<View>(R.id.constraint_layout)

        val redButton = findViewById<TextView>(R.id.red_button)
        val greenButton = findViewById<TextView>(R.id.green_button)
        val yellowButton = findViewById<TextView>(R.id.yellow_button)

        val clickableViews: List<View> =
            listOf(
                boxOneText, boxTwoText, boxThreeText,
                boxFourText, boxFiveText, rootConstraintLayout,
                redButton, greenButton, yellowButton
            )
...
        }
    }
```
