### ISSUE TITLE
Android Kotlin Fundamentals codelab: await() function attempted on non-Deferred object

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#368]
Location in codelab:
Lesson: Android Kotlin Fundamentals 09.1: Repository
Task: 7. Task: Create a repository
Step: Step 1: Add a repository
Numbered statement: 5

It states (for VideosRepository.kt, inside the refreshVideos function):

> Inside the withContext block, fetch the DevByte video playlist from the network using the Retrofit service instance, DevByteNetwork. Use the await() function to suspend the coroutine until the playlist is available.
`val playlist = DevByteNetwork.devbytes.getPlaylist().await()` 

This causes a compile time error because getPlayList() is not a Deferred type.  getPlayList() is defined as:
`suspend fun getPlaylist(): NetworkVideoContainer`

I checked the solution code's VideosRepository.kt code, and it does NOT have await() either.
So both the instruction to add await() and the code snippet are incorrect.

**Comment by jtavva** [comment]
@ken-brown 
Thank you for reaching out to us.
Fixed in the codelab https://codelabs.developers.google.com/codelabs/kotlin-android-training-repository/index.html?index=..%2F..android-kotlin-fundamentals#6
