### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by caalar** [google-developer-training/android-kotlin-fundamentals-apps#37]
There is a typo in an end-of-section questionnaire as shown below:

_"What else do you need to do so that when the user taps the Show headlines button, the app navigates to the **ShowHeadlinesFragment?**"_

It should have been _HeadlinesFragment_ instead of _**Show**HeadlinesFragment_

The issue can be found at:
Lesson number: 03.2 + Step number: 14 + Question: 6

**Comment by GeneAndGoogle** [comment]
Thanks for catching this. Fixed.
