### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by yiar** [google-developer-training/android-kotlin-fundamentals-apps#372]
**Describe the problem**
A clear and concise description of what the problem is.

"1. Open activity_layout.xml in the Text tab."

should be

"1. Open activity_main.xml in the Text tab."

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

https://codelabs.developers.google.com/codelabs/kotlin-android-training-images-compat/#4

step 1

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?

4.0.1
2. What API level are you targeting?

29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
