### ISSUE TITLE
Android Kotlin Fundamentals codelab: Unable to access Mars Web Service API

### ISSUE THREAD

**Issue by adjajaspeedwell** [google-developer-training/android-kotlin-fundamentals-apps#373]
**Describe the problem**
Unable to access the content on the Mars Real Estate web service.  If I try to access the URLs via a web browser, I get a Privacy error (Your connection is not private) page.  The error returned by Chrome is NET::ERR_CERT_AUTHORITY_INVALID.

If you try to proceed regardless with the tutorial, you will not be able to retrieve images as expected in the app.  Early on in the tutorial, you will receive an error message "trust anchor for certification path not found" rendered in the TextView.

**In which lesson and step of the codelab can this issue be found?**
Getting data from the internet - Step 4

**How to reproduce?**
Try to access https://android-kotlin-fun-mars-server.appspot.com or https://android-kotlin-fun-mars-server.appspot.com/realestate

**Versions**
1. Android Studio 4.0.1
2. API Level 30

**Additional information**
It appears the certificate expires on September 6, 2020.

Site failed to load on the following browsers:
- Google Chrome v85.0.4183.83 Windows 64-bit
- Mozilla Firefox 79.0 Windows 64-bit
- Mozilla Firefox 80.0.1 Windows 64-bit

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
We are not able to reproduce this issue on our end.

Please try following from your end
- Try running the app on a different device
- Restarting the emulator 
- Create a new emulator
