### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by lucagavazzeni** [google-developer-training/android-kotlin-fundamentals-apps#374]
**Describe the problem**
I find the word "die" instead of "dice"

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 01.3: Image resources and compatibility + 5. Task: Use a default image.

**How to reproduce?**
In this lesson appear the word "die" instead of "dice" 4 times.

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
