### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by karsie** [google-developer-training/android-kotlin-fundamentals-apps#375]
**Describe the problem**
This task tells to declare the buttons in the MainActivity code, but the examples are using the wrong typing.
`val redButton = findViewById<TextView>` while it should be: `val redButton = findViewById<Button>`

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 02.3 Task 12

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
