### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by karsie** [google-developer-training/android-kotlin-fundamentals-apps#376]
**Describe the problem**
The default package for the empty activity doesn't contain `android` when defining `<variable
       name="myName"
       type="com.example.android.aboutme.MyName" />`

**In which lesson and step of the codelab can this issue be found?**
02.4: step 4.

**How to reproduce?**
Create the new MyName class in com.example.aboutme (the default package for the empty activity template)

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
