### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ced9010** [google-developer-training/android-kotlin-fundamentals-apps#377]
**Describe the problem**
The given classpath for navigation safe args plugin is not working.

**In which lesson and step of the codelab can this issue be found?**
Lesson 3.3 (Start an external activity) Step 3

**How to reproduce?**
trying to build the gradle file with "classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion""

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 29

**Additional information**
solution was to use "classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
"

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
