### ISSUE TITLE
Android Kotlin Fundamentals codelab: material design library version out of date

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#380]
**Describe the problem**
A clear and concise description of what the problem is.
In the codelab the material design library version in gradle is not what is in the sample code.  The sample code has
`implementation 'com.google.android.material:material:1.2.0'`
whereas the codelab text says:
`implementation 'com.google.android.material:material:1.1.0-alpha04'`

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Lesson: Kotlin Android Fundamentals: Material Design, dimens, and colors
Task: 3. Task: Add a floating action button (FAB)
Step: Step 1: Add a FAB to the home fragment layout
Numbered statement: 2

**How to reproduce?**
What are the exact steps to reproduce the problem?
Observe the code snippet in codelab and compare it to the actual material library version in build.gradle(Module: app).

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
