### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by rmacrino** [google-developer-training/android-kotlin-fundamentals-apps#381]
**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Lesson number= Android Kotlin Fundamentals 02.1: Linear layout using the Layout Editor
Step 2
"...1 In the Attributes pane, click the three dots next to the text attribute that you set to your name.
 The resource editor opens....."

three dots not exist in Attributes pane in android studio new version

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@rmacrino 
Thank you for reaching out to us.
This should be fixed now.
Feel free to reopen if needed.
