### ISSUE TITLE
Android Kotlin Fundamentals codelab: Incorrect classpath being used for the safe-args dependency.

### ISSUE THREAD

**Issue by varad64** [google-developer-training/android-kotlin-fundamentals-apps#383]
**Wrong classpath used for the safe-args plugin**
The codelab currently uses a pre-androidX dependency while using the latest stable release of Navigation: 2.3.0  which causes the Gradle Build process to fail.

Using ````classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"```` instead of the existing code````classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$nav_version"```` solves the problem.

**Android Kotlin Fundamentals 03.3: Start an External Activity**
Lesson number  = 3
Step number = 3.

**How to reproduce?**
What are the exact steps to reproduce the problem?
Using the code as it is causes the build to fail since the wrong classpath for the safe-args plugin is being used.

**Versions**
1. What version of Android Studio are you using?
    4.0.1

2. What API level are you targeting?
    API Level 30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by CarterChen247** [comment]
I'm facing the same problem and the solution above solved it

**Comment by jtavva** [comment]
@varad64

Thank you for reaching out to us.
Can you please provide more details? 
**Codelab name:**
**App name:**

**Comment by varad64** [comment]
> @varad64
> 
> Thank you for reaching out to us.
> Can you please provide more details?
> **Codelab name:**  Android Kotlin Fundamentals 03.3 (Lesson 3, Step 3) : Start an External Activity
> **App name:** Android Trivia

**Comment by jtavva** [comment]
Fixed! 
Thank you for reaching out to us.
