### ISSUE TITLE
Android Kotlin Fundamentals codelab: Android Kotlin Fundamentals 07.2

### ISSUE THREAD

**Issue by mmaia** [google-developer-training/android-kotlin-fundamentals-apps#384]
**Describe the problem**
Wrong method name refered in step in lab

**In which lesson and step of the codelab can this issue be found?**
6 +  2.

**How to reproduce?**
Check item list 2 it says: `2. In the ViewHolder class, find the from() method.`

There's no `from()` method in the class, is should be instead: `onCreateViewHolder`

**Versions**
Not applicable

**Additional information**
Documentation issue

**codelab:** android-kotlin-fundamentals 07.02

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
