### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by kolanse** [google-developer-training/android-kotlin-fundamentals-apps#385]
The MoshiConverter import statements are not working because you didn't instruct learners to import the necessary depedency

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
Can you please give me the following details.

**Codelab name:**
**App name:**

**Comment by jtavva** [comment]
@kolanse 
It's been more than a month since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.
