### ISSUE TITLE
Android Kotlin Fundamentals codelab: "Talkback" misspelled as "Talback"

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#392]
**Describe the problem**
A clear and concise description of what the problem is.
The word "Talkback" is misspelled as "Talback"

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

Lesson: _Kotlin Android Fundamentals: Design for everyone_
Task: 5. _Task: Design for TalkBack_
Step: _Step 3: Add hints to editable text fields_
Numbered statement: _6_

> Run your app with Talback enabled, and fill out the form to apply to run a GDG.

**How to reproduce?**
What are the exact steps to reproduce the problem?
Read specified text in codelab

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
