### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#395]
**Describe the problem**
A clear and concise description of what the problem is.
The code snippet in the given section is incorrect as it has nested "val children..." statements, whereas the final lambda content only has a single "val children..." statement.
The incorrect snippet has this:
`val children = data.map {
   val children = data.map { regionName ->
       val chip = inflator.inflate(R.layout.region, chipGroup, false) as Chip
       chip.text = regionName
       chip.tag = regionName
       // TODO: Click listener goes here.
       chip
   }
}`

Notice that the final snippet at end of this Task does not:
`       val children = data.map { regionName ->
           val chip = inflator.inflate(R.layout.region, chipGroup, false) as Chip
           chip.text = regionName
           chip.tag = regionName
           chip.setOnCheckedChangeListener { button, isChecked ->
               viewModel.onFilterChanged(button.tag as String, isChecked)
           }
           chip
       }
 `

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Lesson: Kotlin Android Fundamentals: Design for everyone
Task: 6. Task: Use chips to filter regions
Step: Step 2: Display the row of chips
Numbered statement: 7

**How to reproduce?**
What are the exact steps to reproduce the problem?
Examine the code snippet in Step 2 numbered statement 7 against the final snippet in this step and observe the inconsistency in code around `val children = data.map {}`

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 28

**Additional information**
Removing the outer `val children = data.map {}` produces the correct code.

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
same as #394
