### ISSUE TITLE
Android Kotlin Fundamentals codelab: 03.3: Start an external activity

### ISSUE THREAD

**Issue by michaeloverman** [google-developer-training/android-kotlin-fundamentals-apps#399]
Instruction with code to be included is out of date.
03.3: Start an external activity, Step 3
Add safeargs gradle plugin dependency to project level gradle file. Instructions say:

`// Adding the safe-args dependency to the project Gradle file
dependencies {
   ...
classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

}`

Should be:
`// Adding the safe-args dependency to the project Gradle file
dependencies {
   ...
classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"

}`

...as per documentation which can be found here: https://developer.android.com/jetpack/androidx/releases/navigation

This also fixes the $nav_version variable name incongruity, for anyone working through all the tutorials, and not starting this tutorial with the provided starter code.

Found on Android Studio 4.0.1, target and compile SDK=30, minSdk=19

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
