### ISSUE TITLE
How to fix KotlinNullPointerException in LiveData when attempting to get a value (DevBytesRepository)

### ISSUE THREAD

**Issue by Holofox** [google-developer-training/android-kotlin-fundamentals-apps#4]
In my application, the condition: `if (playlist.value!!.IsEmpty())` causes a kotlin.KotlinNullPointerException.

```kotlin    
class DevByteViewModel(application: Application) : AndroidViewModel(application) {
    
    ...
    
    val playlist = videosRepository.videos
    
    ...
    
    init {
        refreshDataFromRepository()
    }
    
    ...
    
     /**
     * Refresh data from the repository. Use a coroutine launch to run in a
     * background thread.
     */
    private fun refreshDataFromRepository() {
        viewModelScope.launch {
            try {
                videosRepository.refreshVideos()
                _eventNetworkError.value = false
                _isNetworkErrorShown.value = false

            } catch (networkError: IOException) {
                // Show a Toast error message and hide the progress bar.
                if(playlist.value!!.isEmpty())
                    _eventNetworkError.value = true
            }
        }
    }
}
```
The fact is,
1. Asynctask is running on another thread in background asynchronously
2. Livedata is working like floating over database to see the changes.

So it takes time to accomplish the fetch operation for Asyntask. I want to understand how to avoid it. Thanks.

**Comment by jtavva** [comment]
Hello @Holofox,
Thank you for reaching out to us. Which app are you referring to, is it DevBytesRepository or DevBytesWorkManager?

**Comment by Holofox** [comment]
@jtavva, DevBytesRepository.

**Comment by jtavva** [comment]
Thank you for your feedback.  This is fixed now in the pull request, https://github.com/google-developer-training/android-kotlin-fundamentals-apps/pull/23.
