### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by adesanyaaa** [google-developer-training/android-kotlin-fundamentals-apps#40]
**Describe the problem**
A clear and concise description of what the problem is.
Android Kotlin Fundamentals 04.2: Complex lifecycle situations

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Step 2: Modify MainActivity
Remove the call to startTimer() in onStart() not
remove the call to startTimer() in onCreate()
end of issue
**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
I think the codelab is correct now, but reopen if you still see the issue. Thanks!
