### ISSUE TITLE
Android Kotlin Fundamentals codelab: Start an external Activity

### ISSUE THREAD

**Issue by michaeloverman** [google-developer-training/android-kotlin-fundamentals-apps#400]
Android Kotlin Fundamentals codelab: Start an External Activity
Task 5, Step 2, Number 3, Use getShareIntent()
In the code sample, isVisible should be false. Here is the code as it is currently:
```// Showing the Share Menu Item Dynamically
override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
       super.onCreateOptionsMenu(menu, inflater)
       inflater.inflate(R.menu.winner_menu, menu)
       if(getShareIntent().resolveActivity(requireActivity().packageManager)==null){
            menu.findItem(R.id.share).isVisible = true
       }
}
```
Last line, though, should be `false` because that is called when an resolveActivity returns null, and thus the sharing can not happen.

I am using Android Studio 4.0.1, target and compileSdk 30, minSdk 19.

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
