### ISSUE TITLE
Android Kotlin Fundamentals codelab: some lesson not indexed like fragment lesson, so, I keep tracking the lesson by the index, Thanks it's awesome work

### ISSUE THREAD

**Issue by alfatih7** [google-developer-training/android-kotlin-fundamentals-apps#401]
**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
Is there anyway we can help you with?

**Comment by jtavva** [comment]
@alfatih7 
It's been more than a month since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.

**Comment by alfatih7** [comment]
I'm so sorry for late, I study well for android kotlin fundamentals codelab, I just note that the indexing at first time not well but at the end of tutorial you can see the indexing 
thanks, 
Alfatih Abdelmutalib
