### ISSUE TITLE
Android Kotlin Fundamentals codelab: 07.3: GridLayout with RecyclerView

### ISSUE THREAD

**Issue by SodaCris** [google-developer-training/android-kotlin-fundamentals-apps#403]
**Describe the problem**
A clear and concise description of what the problem is.

![image](https://user-images.githubusercontent.com/24788699/93062607-ca2adf00-f6a7-11ea-99eb-9bebe1f56891.png)

the first(the upper) should be VERTICAL, and the second should be horizontal.

**In which lesson and step of the codelab can this issue be found?**

Lesson 07.3, step 4, at the end of this step.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
