### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by behrends** [google-developer-training/android-kotlin-fundamentals-apps#404]
**Describe the problem**
The dependency for `navigation-fragment-ktx` is not included in the `build.gradle` snippet.

**In which lesson and step of the codelab can this issue be found?**
Lesson 3, Step 1.4

**How to reproduce?**
The text mentions to include `navigation-fragment-ktx`. However the code below shows this:

```
dependencies {
  ...
  implementation "androidx.navigation:navigation-fragment:$nav_version"
  implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
  ...
}
```

Note the missing suffix `-ktx` above. To fix this, the code snippet should look like this (add `-ktx`):

```
dependencies {
  ...
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
  implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
  ...
}
```

**Versions**
1. 4.0.1
2. 29

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@behrends 
Thank you for reaching out to us.
Can you provide us the link to the codelab or the full name of the codelab, please.

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
