### ISSUE TITLE
Android Kotlin Fundamentals codelab: Loading and displaying images from the internet

### ISSUE THREAD

**Issue by agalfioni** [google-developer-training/android-kotlin-fundamentals-apps#405]
**Describe the problem**
Missing Target JVM version configuration

**In which lesson and step of the codelab can this issue be found?**
Lesson 3 + step 3.

**How to reproduce?**
- Clone indicated project.
- Follow all steps in codelab including step 3 of lesson 3.

**Versions**
1. What version of Android Studio are you using?
4.0.1
2. What API level are you targeting?
30

**Additional information**
The error is: "Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6"

Solution: Add in Gradle:
`kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }`

**codelab:** android-kotlin-fundamentals: Loading and displaying images from the internet

**Comment by jtavva** [comment]
@agalfioni 
Thank you for reaching out to us.
Can you please give the following details:

- **Codelab url:**
- **Github URL of solution code:**

**Comment by jtavva** [comment]
@agalfioni 
It's been more than a month since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.
