### ISSUE TITLE
Android Kotlin Fundamentals codelab: Android Kotlin Fundamentals: Repository

### ISSUE THREAD

**Issue by michaeloverman** [google-developer-training/android-kotlin-fundamentals-apps#407]
I received an error on the initial build due to the AppTheme not being a descendent of MaterialComponents. I changed this line from res/values/styles:
`<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">`
to:
`<style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">`
and it worked.

**Comment by Stephen-Odumirin** [comment]
Nice

**Comment by jtavva** [comment]
@michaeloverman 
Thank you for reaching out to us.
Please provide us with the following details:
Codelab name or URL:
Task:
Step:
App name:

**Comment by jtavva** [comment]
@michaeloverman 
It's been28 days since we've heard from you, so we are going to close this ticket. You can always reopen this issue or raise a new one if you need any further assistance.
