### ISSUE TITLE
Android Kotlin Fundamentals codelab: 7.3 Grid Layout TextView Error on Track My Sleep Quality app

### ISSUE THREAD

**Issue by Osunator** [google-developer-training/android-kotlin-fundamentals-apps#411]
**Describe the problem**
It isn't a problem that generates any kind of compilation error, it's an interface error. The text of the **"quality_string" Textview** on the **Track My Sleep Quality** app gets cut when the view is changed into a grid.

As it can be seen in the image below the qualities that are 4 that should be **"Pretty good"** only say **"Pretty"**, also the qualities that are 5 only say **"Excellent"** without the exclamation mark **"!"** at the end because the text is cut:

![image](https://user-images.githubusercontent.com/68091595/93647125-e9d24800-f9c4-11ea-8b02-e2e162abe1d0.png)

This happens because in the code given for the layout change it says:

   **app:layout_constraintEnd_toEndOf="@+id/quality_image"**
   **app:layout_constraintStart_toStartOf="@+id/quality_image"**

Making the width of the TextView to be cut and also because the way of the image has the quality number on the right it looks like the text isn't centered. 

**In which lesson and step of the codelab can this issue be found?**
Lesson 7.3 - GridLayout with RecyclerView at Task 4 - Implement Grid Layout in Step 2 - Change the layout 

**How to reproduce?**
Just follow the instructions of the task

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 14

**Additional information**
This can be fixed very easily because the properties of the RecyclerView, since the LayoutManager defines the span size fitting the layout given equally in the number of spans, we can draw the ImageView and TextView centered in the layout and RecyclerView moves them to the correct position. We can do it like this:

![image](https://user-images.githubusercontent.com/68091595/93649963-792e2a00-f9ca-11ea-8cac-b7ae35a7ae8d.png)

The updated code on the **"quality_string" TextView** to be almost centered in the layout but a little more to the left to looked centered with the **"quality_image" ImageView** is: 

        <TextView
            android:id="@+id/quality_string"
            android:layout_width="0dp"
            android:layout_height="20dp"
            android:layout_marginEnd="15dp"
            android:textAlignment="center"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/quality_image"
            app:sleepQualityString="@{sleep}"
            tools:text="Excellent!!!" />

Also to center the **"quality_image" ImageView** we need to delete in the code:

       android:layout_marginStart="16dp"

And we need to add:

       app:layout_constraintEnd_toEndOf="parent"

With that the text of the **"quality_string" TextView** gets printed completely and centered, like the following image:

![image](https://user-images.githubusercontent.com/68091595/93650176-0b363280-f9cb-11ea-894a-8c72851b6c77.png)

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@Osunator 
Thank you for reaching out to us.
This should be fixed now.
