### ISSUE TITLE
Android Kotlin Fundamentals codelab: Repository: Wrong place for the dealy code

### ISSUE THREAD

**Issue by daskelly45** [google-developer-training/android-kotlin-fundamentals-apps#413]
In the Android Kotlin Fundamentals code labs series, specifically in the Repository codelab during the first task. 

It was asked to explore the app and to simulate the network latency by suspending the coroutine that is used to fetch data from network. But in the provided snippet the delay code was put inside the catch block of code. 

Shouldn't the delay code be rather placed at the top of the try block to indeed suspend the coroutine from making the network call and thereby letting the spinner visible much longer on the screen ?

**Comment by jtavva** [comment]
@daskelly45 
Thank you for reaching out to us.
The reason delay statement is placed in the catch block above the statement `_eventNetworkError.value = true` is, this delay will delay setting the network error. So there is time to see the loading spinner.  
The description for this step is updated and will be published soon.
