### ISSUE TITLE
Gaps in courses numbers( e.g. 7.1 , next is 7.4) or removed numbers. Not clear what courses cover same code project.

### ISSUE THREAD

**Issue by anotheraccountusername** [google-developer-training/android-kotlin-fundamentals-apps#415]
**Describe the problem**
The codes for courses are disappeared from the Titles. Takes time to identify courses related to same group/code-project/topic. 

**In which lesson and step of the codelab can this issue be found?**
Through out the "Anrdoid Kotlin Fundamentals" course.

**Comment by jtavva** [comment]
@anotheraccountusername 
Thank you for reaching out to us.
we are in the process of fixing this, please refer to course overview page for time being. 
https://developer.android.com/courses/kotlin-android-fundamentals/toc?authuser=1
