### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by houssam-MIMI** [google-developer-training/android-kotlin-fundamentals-apps#416]
**Describe the problem**
I found a preblem in first step of this cours when I want to run the app for first time  
the app is GDG-finder starter app.
and its provide this problem : 
java.lang.RuntimeException: Canvas: trying to draw too large(124597440bytes) bitmap.

**In which lesson and step of the codelab can this issue be found?**
Styles and themes + 4

**How to reproduce?**
I download the app from github when I want to run it for the first time  , the app  is closed , because its provide this probleme 
java.lang.RuntimeException: Canvas: trying to draw too large(124597440bytes) bitmap.  

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@houssam-MIMI 
Please provide us with the following details:
Emulator or device profile

1. Model : 
2. Android version(Target) :

**Comment by jtavva** [comment]
@houssam-MIMI 
Thank you for reaching out to us.
It's been 14 days since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.
