### ISSUE TITLE
Android Kotlin Fundamentals codelab: 05.2: LiveData and LiveData observers

### ISSUE THREAD

**Issue by GBenoitG** [google-developer-training/android-kotlin-fundamentals-apps#417]
**Describe the problem**
The "correct" button continues to display the toast even if the fix is applied. Because each time the button is clicked the *nextWord()* function is called so the *_eventGameFinish* is always on *true* value.

**In which lesson and step of the codelab can this issue be found?**
task 7 - step 2

**How to reproduce?**
Follow the actual step then build the app and click the *correct* button

**Versions**
1. *Android Studio v4.0.1 + gradle v6.1.1*
2. *targetSdkVersion 30*

**Additional information**
After following strickly all steps in the task 7 step 2 point 3 just before uncommenting the navigation code.

**codelab:** android-kotlin-fundamentals 05.2: LiveData and LiveData observers

**Comment by jtavva** [comment]
After 21 words, the game should end and the score fragment is displayed. 
Please cross check your code with the solution code: 
https://github.com/google-developer-training/android-kotlin-fundamentals-apps/tree/master/GuessTheWordLiveData
