### ISSUE TITLE
Android Kotlin Fundamentals codelab: Moshi 1.5 ignores @Json annotation on Kotlin class properties 

### ISSUE THREAD

**Issue by Osunator** [google-developer-training/android-kotlin-fundamentals-apps#418]
**Describe the problem**
The "@JSON" doesn't displays correctly since Moshi 1.5 on Kotlin
On this task you are asked to change the text of the TextView to display the address of the images you get from internet, but it doesn't display anything, because using the code "@Json(name = "img_src") val imgSrcUrl: String" doesn't work.

After checking this website https://github.com/square/moshi/issues/315 I found that the problem was the new version of Moshi on Kotlin and had to use the workaround "@field:Json"

So changing the code to "@field:Json(name = "img_src") val imgSrcUrl: String" fixes this and the address is shown in the TextView. This also fixes the value for the address of the images that need to be shown in the following steps.

**In which lesson and step of the codelab can this issue be found?**
It can be viewed in "8.2 - Loading and displaying images from the internet" on Task 3 at Step 2 when you change the TextView android:text="@{viewModel.property.imgSrcUrl}" but this is defined since "8.1 - Getting data from the internet" on Task 5 at Step 2

**How to reproduce?**
Just need to follow the 8.2 lesson code and it happens almost at the start, @Json simply creates the variable but doesn't add the text, if you continue with the next steps because the variable is left blank it doesn't even show the imagen on Step 4.

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 19

**Additional information**
If you don't use JSON at all and leave the name of the variable "img_src" everything works correctly, but it doesn't cover how to change the name of a variable in case the variable name has an space or something that can't be use as a name. 

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@Osunator 
Thank you for reaching out to us. we are not able to reproduce the issue. 
Please cross check your code with the solution code. 
https://github.com/google-developer-training/android-kotlin-fundamentals-apps/tree/master/MarsRealEstateNetwork

**Comment by Osunator** [comment]
I cross check my code with the SOLUTION CODE and I found 4 differences, but the one that gives this error is the @JSON.

In the **STARTER** code on the **BUILD.GRADLE (PROJECT)** it's declared **version_moshi = "1.8.0"** but on the solution code the version declared is **version_moshi = "1.9.3"**. When I tried changing that in the code, the whole app failed giving me the network error, I tried using a NEXUS 5X API 25 emulator to check if the problem was my phone, but as you can see in the next images the error was the same.

![LG Stylus 4 - 3](https://user-images.githubusercontent.com/68091595/95389401-01f50300-08b1-11eb-9cc3-ddbd66b2cba5.png)
![NEXUS 5X API25 - 3](https://user-images.githubusercontent.com/68091595/95388407-7e86e200-08af-11eb-8384-013c19e6ba30.png)

The **STARTER** code on the **BUILD.GRADLE (PROJECT)** is missing the following lines **version_kotlin_coroutines = "1.3.7"** and **version_retrofit_coroutines_adapter = "0.9.2"** but that doesn't change anything.

The only difference in the code is in the **MarsProperty.kt** on the line **@Json(name = "img_src") val imgSrcUrl: String,** leaving it like that it doesn't show me any images, because it can't find the address of the code as you can see in the screenshots from the next images.

![LG Stylus 4 - 1](https://user-images.githubusercontent.com/68091595/95389403-028d9980-08b1-11eb-8407-1ac7ff4be35c.png)
![NEXUS 5X API25 - 1](https://user-images.githubusercontent.com/68091595/95388401-7af35b00-08af-11eb-87ad-99ff0a0a825f.png)

This can be fixed when changing the line to **@field:Json(name = "img_src") val imgSrcUrl: String,** or simply leaving the line as **val img_src : String,** doing this gives the next images.

![NEXUS 5X API25 - 2](https://user-images.githubusercontent.com/68091595/95388403-7b8bf180-08af-11eb-8749-3da04dadd9ee.png)
![LG Stylus 4 - 2](https://user-images.githubusercontent.com/68091595/95389408-028d9980-08b1-11eb-90d1-93a189ca5565.png)

I don't know if the error has something to do with the Moshi Version that I can't change, but I have the Android Studio and SDK Manager updated. I have attached the imagen of the Android Studio version I use and the phone I use to test the apps is an LG Stylus 4 with an Android Version 9 Kernel Version 3.18.120.

![Android Studio Version](https://user-images.githubusercontent.com/68091595/95388396-7a5ac480-08af-11eb-84de-6bf4ab42786b.PNG)
