### ISSUE TITLE
Android Kotlin Fundamentals codelab 8.1: 

### ISSUE THREAD

**Issue by Zectrotech** [google-developer-training/android-kotlin-fundamentals-apps#420]
**Describe the problem**
The Gradle build file (module: app) has erroneous code. When you try to build it the way that it says in the codelab, it produces an error message stating that the jvmtarget() method was not found.

**In which lesson and step of the codelab can this issue be found?**
Lesson 4, Step 2

**How to reproduce?**
Enter the code as stated in the codelab on this step and attempt to sync Gradle files.

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 30 (min 21)

**Additional information**
I was able to resolve the issue by entering it like so:

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8

        kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8
}

I got an a few warnings about deprecated Gradle and Kotlin features in the build screen.

**codelab:** android-kotlin-fundamentals 8.1

**Comment by jtavva** [comment]
@Zectrotech 
Thank you for reaching out to us.
Please give us the following details:

- What is your Kotlin pulgin version (version_kotlin): 
- Do you have the following library included in your dependencies section?   
`implementation "org.jetbrains.kotlin:kotlin-stdlib:$version_kotlin"`

**Comment by Zectrotech** [comment]
1.3.72 and yes, I do

**Comment by Zectrotech** [comment]
sorry, I meant to send this one

**Comment by jtavva** [comment]
@Zectrotech 
Thank you for reaching out to us. Glad you could resolve your issue.
