### ISSUE TITLE
Android Kotlin Fundamentals codelab: Initialize view models using KTX lazy delegate

### ISSUE THREAD

**Issue by secretshardul** [google-developer-training/android-kotlin-fundamentals-apps#421]
**Describe the problem**
Current examples use the java class based syntax to initialize view models. For example
```kotlin
viewModel = ViewModelProvider(this).get(GameViewModel::class.java)
```

Using `androidx.fragment:fragment-ktx:1.2.5` library we can initialize viewmodels in a more idiomatic manner
```kotlin
val viewModel: GameViewModel by viewModels()
```

I propose that this should be the recommended approach and the codebase should be updated accordingly.

**In which lesson and step of the codelab can this issue be found?**
[Lesson 5 + step 5](https://codelabs.developers.google.com/codelabs/kotlin-android-training-view-model/index.html?index=..%2F..android-kotlin-fundamentals#4)

**How to reproduce?**
Visit [GameFragment.kt](https://github.com/google-developer-training/android-kotlin-fundamentals-apps/blob/3684f0a735ea535cbf2f88b67b0915612f8ae886/GuessTheWordViewModel/app/src/main/java/com/example/android/guesstheword/screens/game/GameFragment.kt#L54)

**Versions**
1. What version of Android Studio are you using?
NA
2. What API level are you targeting?
NA

**Additional information**
NA

**codelab:** android-kotlin-fundamentals

**Comment by secretshardul** [comment]
Made changes to [GuessTheWordViewModel](https://github.com/google-developer-training/android-kotlin-fundamentals-apps/tree/master/GuessTheWordViewModel) project. Check out #422

**Comment by jtavva** [comment]
@secretshardul 
There are two ways to initialize ViewModel, you can do it using  ViewModelProvider, as shown in the reference documentation, [ViewModel](https://developer.android.com/reference/androidx/lifecycle/ViewModel#public-constructors).
Closing the issue for now.
