### ISSUE TITLE
Android Kotlin Fundamentals codelab: Ambiguous code

### ISSUE THREAD

**Issue by osmium8** [google-developer-training/android-kotlin-fundamentals-apps#423]
**Describe the problem**
Ambiguity in the usage of "myName" _variable/data-class/reference_

**In which lesson and step of the codelab can this issue be found?**
Lesson 4 ( step 2 & step 3 )

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@osmium8 
Thank you for reaching out to us. 
Can you please give the name of the codelab?

**Comment by osmium8** [comment]
Data binding

https://codelabs.developers.google.com/codelabs/kotlin-android-training-data-binding-basics/#3

**Comment by jtavva** [comment]
@osmium8 
Thank you for reaching out to us.
`Myname` is a data class with two string variables- `name` and `nickname`.
To learn more on how to use  classes in Kotlin please refer the following codelab.
https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-classes/#8
