### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [google-developer-training/android-kotlin-fundamentals-apps#424]
**Describe the problem**
Typographical error ( should be replaced with GameViewModel instead of GameFragment )

**In which lesson and step of the codelab can this issue be found?**
Lesson number-6  and  step number-1, the following line needs correction
(You can delete the log statement in the init block of GameFragment)

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@kpradeepkumarreddy 
Thank you so much for reporting this issue. This is fixed and will be published soon.
