### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by leiflundberg** [google-developer-training/android-kotlin-fundamentals-apps#425]
**Describe the problem**
The button placement has changed and screenshot must be updated.

**In which lesson and step of the codelab can this issue be found?**
01.2 + 2.2

**How to reproduce?**
Open Android Studio activity_main.xml file.

**Versions**
1. What version of Android Studio are you using?
4.0.1
2. What API level are you targeting?
30

**Additional information**
<img width="1029" alt="Screenshot 2020-10-04 at 17 42 39" src="https://user-images.githubusercontent.com/41685083/95020124-86554500-0669-11eb-9962-5e0ad0ba2531.png">

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@leiflundberg 
Thank you for reaching out to us.
can you tell us which screen shot you are referring to, and the codelab name?

**Comment by leiflundberg** [comment]
Hi!

I am following the "Android Kotlin Fundamentals Course" and noticed that
most of the screenshots are for an older version of Android Studio and that
can be quite confusing for someone that is new to the IDE. For example, in
this
<https://codelabs.developers.google.com/codelabs/kotlin-android-training-images-compat/index.html?index=..%2F..android-kotlin-fundamentals#2>
codelab,
the second image shows that you must click on the "design" pane. This
doesn't exist in my version and has been replaced by "Code, Split and
Design" buttons in the top right corner. Please see attached screenshot.

I am very much enjoying the course, so thank you and have a great day!
