### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ali-afk-code** [google-developer-training/android-kotlin-fundamentals-apps#426]
**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals: Coroutines and Room  ->6. Task: Collect and display the data->Step 2: Set up coroutines for database operations

**How to reproduce?**
after 2nd step it is 6th step
**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
