### ISSUE TITLE
Android Kotlin Fundamentals: ViewModel

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [google-developer-training/android-kotlin-fundamentals-apps#427]
**Describe the problem**
Is it possible to write a generic ViewModelFactory class that works for all ViewModels ?

**In which lesson and step of the codelab can this issue be found?**
Lesson number-8 + step number-5

**Comment by jtavva** [comment]
@kpradeepkumarreddy 
Yes it is possible!
Please take look at the documentation on how to implement it- [Share data between fragments](https://developer.android.com/topic/libraries/architecture/viewmodel#sharing).

Hope this helps.

**Comment by kpradeepkumarreddy** [comment]
> @kpradeepkumarreddy
> Yes it is possible!
> Please take look at the documentation on how to implement it- [Share data between fragments](https://developer.android.com/topic/libraries/architecture/viewmodel#sharing).
> 
> Hope this helps.

Sorry. I could not find it. If possible, can you please copy paste the code here ? I found one answer from stackoverflow, but i have doubt if it is the recommended way to do it or not. Here is the code that i found from stackoverflow
`object MyViewModelsFactory : ViewModelProvider.Factory {
    private val viewModelMap: HashMap<String, ViewModel>? = HashMap()

    fun add(viewModel: ViewModel) {
        viewModelMap!![viewModel.javaClass.simpleName] = viewModel
    }

    override fun <T : ViewModel?> create(modelClass: Class<T>): T {
        for ((key, value) in viewModelMap!!) {
            if (key == modelClass.simpleName) {
                return value as T
            }
        }
        return null as T
    }
}`

The problem with the above code is that we ourselves have to create ViewModel instance and add it to HashMap in ViewModelFactory class. But according to what i read about viewmodels, we should not create instances of viewmodels ourselves, instead it should be done by ViewModelProvider.  As of now, i'm following whatever is given in the following codelab
https://codelabs.developers.google.com/codelabs/kotlin-android-training-view-model/#0
As of now i created a ViewModelFactory class for every viewmodel. But instead of writing so many factory classes, is it possible to write a generic ViewModelFactory class that works for all the viewmodels in my app ??

**Comment by jtavva** [comment]
Please click on the link
https://developer.android.com/topic/libraries/architecture/viewmodel#sharing

**Comment by kpradeepkumarreddy** [comment]
> Please click on the link
> https://developer.android.com/topic/libraries/architecture/viewmodel#sharing

Yes i already checked that link, but i did not find the answer for my question.
