### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by nike2lim** [google-developer-training/android-kotlin-fundamentals-apps#428]
**Describe the problem**
A clear and concise description of what the problem is.

=> 
The details of getting the viewModel are not detailed.
I need the code to import it like below.

viewModel = ViewModelProvider(this).get(GameViewModel::class.java) or 
viewMdoel : GameViewModel by viewModels()       // activity-ktx

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
=> Lesson Number : 4, step number : 1

**How to reproduce?**
What are the exact steps to reproduce the problem?
=> Below is the page in question.
https://developer.android.com/codelabs/kotlin-android-training-live-data-data-binding#3

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@nike2lim 
Thank you for reaching out to us.
Adding the ViewModel is covered in the previous codelab: [Android Kotlin Fundamentals: 5.1 ViewModel](https://codelabs.developers.google.com/codelabs/kotlin-android-training-view-model/index.html?index=..%2F..android-kotlin-fundamentals#4)

Hope this helps.
