### ISSUE TITLE
Android Kotlin Fundamentals: ViewModel

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [google-developer-training/android-kotlin-fundamentals-apps#429]
**Describe the problem**
WordList empty case is not handled on 'got it' button click and also on 'skip' button click

**In which lesson and step of the codelab can this issue be found?**
Lesson number-7 + step number-4

**How to reproduce?**
Keep pressing 'got it' button, after the word list is empty, score will increase but word display text will not change

**Comment by jtavva** [comment]
@kpradeepkumarreddy 
Can you please give us a link of the codelab you are working on?

**Comment by kpradeepkumarreddy** [comment]
> @kpradeepkumarreddy
> Can you please give us a link of the codelab you are working on?

Here it is 
https://codelabs.developers.google.com/codelabs/kotlin-android-training-view-model/#0

**Comment by jtavva** [comment]
@kpradeepkumarreddy 
Thank you for reaching out to us.
This issue will be addressed in the consequent codelabs.
