### ISSUE TITLE
Android Kotlin Fundamentals codelab: In app level build.gradle file . viewBinding is not mentioned 

### ISSUE THREAD

**Issue by OmkarSsawant** [google-developer-training/android-kotlin-fundamentals-apps#430]
## Please mention viewBinding in app level build.gradle file .  

In lesson number 02.4 (Data binding basics) 
### 3. Task: Use data binding to eliminate findViewById()
     > Step 1 (Enable Data Binding)

##### as shown in docs

```gradle
     buildFeatures {
           dataBinding true
   }
```

When you just configure build features as mentioned in this code-lab compiler will not generate a view binding class for layout
only data binding can be done here . So, Instead this code should also include viewBinding too . So , gradel should be configured as follows :

```gradle

     buildFeatures {
           dataBinding true
          viewBinding true
    }

```
 

**Versions**
1.Android Studio version 4.0.1
2. API level 29

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@OmkarSsawant 
Can you help us with more information?
Where in the codelab do we need "_layout only data binding_"?

**Comment by jtavva** [comment]
@OmkarSsawant 
Thank you for reaching out to us.
The solution code seems to be working. 
It's been 14 days since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.
