### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by gabiguetta** [google-developer-training/android-kotlin-fundamentals-apps#431]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-internet-data/#3

**Describe the problem**
There are two "Step 4.": "Step 4: Call the web service in OverviewViewModel" and "Step 4: Define the internet permission"

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@gabiguetta 
Thank you so much for reporting this issue. This is fixed and will be published soon..
