### ISSUE TITLE
Android Kotlin Fundamentals codelab: Design for everyone

### ISSUE THREAD

**Issue by Osunator** [google-developer-training/android-kotlin-fundamentals-apps#433]
**Name of the Codelab or Codelab URL**
Kotlin Android Fundamentals: Design for everyone

**Describe the problem**
There's a mistype on the code, it says to enter the code for the Linear Layout and at the end it says  **"< LinearLayout/ >"** for closing the layout instead of **"< /LinearLayout >"** 
![image](https://user-images.githubusercontent.com/68091595/95668580-48599480-0b33-11eb-920f-f3ce43c6054f.png)

**In which lesson and step of the codelab can this issue be found?**
Not sure what lesson number should be, I believe 9.3 in the **Design for everyone** on **Task 5 - Design for TalkBack** at **Step 4 - Create a content group** 

**How to reproduce?**
Just need to check the code

**Versions**
1. What version of Android Studio are you using? 4.0.2
2. What API level are you targeting? 14

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@Osunator 
Updated the closing tag in the code snippet to `< /LinearLayout >`
Thank you so much for reporting this issue. This is fixed and will be published soon.
