### ISSUE TITLE
Android Kotlin Fundamentals codelab: DiceImages. Dots Not Visible

### ISSUE THREAD

**Issue by DrAferdel** [google-developer-training/android-kotlin-fundamentals-apps#434]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-images-compat/index.html?index=..%2F..android-kotlin-fundamentals#2

**Describe the problem**
A clear and concise description of what the problem is.
The xml documents in DiceImages.zip do not show the dots on the dice in the Design view

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Fundamentals 01.3, Task 3, Step 1

**How to reproduce?**
What are the exact steps to reproduce the problem?
Load xml documents in res/drawable, Design view

**Versions**
1. What version of Android Studio are you using?
Android Studio 4.0.2

2. What API level are you targeting?
API 23

**Additional information**

Replacing ",1 0,-"  by ",0 1,-" in all files solves the problem for me. This exchanges the large-arc-flag and the sweep-flag in the drawing of the ellipses. Replacing fillColor for strokeColor for one of the dots also shows that the dot is being drawn but the path is overlapping itself

**codelab:** android-kotlin-fundamentals

**Comment by DrAferdel** [comment]
On the Design view on Android Studio the dots are not visible but when running it on a physical machine (Android 10) they are, and once the change I suggested is applied, the opposite is true: visible in Android Studio, not visible on the physical machine

**Comment by jtavva** [comment]
@DrAferdel 
Thank you for reaching out to us.
The Dice images are rendered correctly in the latest version of the Android Studio 4.1. 
For your reference:

![image](https://user-images.githubusercontent.com/24260141/96650600-ff9a9c00-12e7-11eb-8e41-d85e5a9bc940.png)
