### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by vpermits** [google-developer-training/android-kotlin-fundamentals-apps#437]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-diffutil-databinding/#5

**Describe the problem**
Starter SleepNightAdapter.kt source code does not match instructions.

**In which lesson and step of the codelab can this issue be found?**
Step 2, #2 "In the **ViewHolder** class, find the onCreateViewHolder() method."  DOES NOT EXIST.

**How to reproduce?**
Use the android-kotlin-fundamentals-starter-apps-master from github.
Open the SleepNightAdapter.kt from the source and notice the onCreateViewHolder is not in the inner class ViewHolder and does not contain the "item" definition.

**Versions**
1. What version of Android Studio are you using? 4.1
2. What API level are you targeting? 30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@vpermits 
Thank you so much for reporting this issue. This is fixed and will be published soon.
