### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by jryan0004** [google-developer-training/android-kotlin-fundamentals-apps#438]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-diffutil-databinding/#5

**Describe the problem**
A clear and concise description of what the problem is.
In the directions of the codelab it states to use "Select Refactor > Inline, or press Control+Command+N (Option+Command+N on a Mac)." to use the short cut on windows but that is false, the command is ctrl+alt+N.
**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Android Kotlin Fundamentals: DiffUtil and data binding with RecyclerView
    6. Task: Use DataBinding with RecyclerView
          Step 3: Replace findViewById()
**How to reproduce?**
What are the exact steps to reproduce the problem?
Read the directions.
**Versions**
1. What version of Android Studio are you using?N/A
2. What API level are you targeting?N/A

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@jryan0004 
Thank you so much for reporting this issue. This is fixed and will be published soon.
