### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by JackDamei** [google-developer-training/android-kotlin-fundamentals-apps#445]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-live-data-transformations/#3

**Describe the problem**
The word list is reset in the "if" statement, and the operation which removes a word is still on the "else" part (which doesn't have a "}" for closure)
So when the app is running, after the 20th word (end of the sample list), the displayed word does not change.
Should not the else be completely removed (it seems logic that it should) ?

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 05.4
    page 4
        step 7

Thank you very much for all these well-explained codelabs. You've done an incredible work so far !

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@JackDamei 
Thank you for reaching out to us.
Added the missing brace in the code snippet in the codelab. It will be published soon.

If we remove the else part, wordlist will not be updated. In the else part we are removing the used word and we pick the next word in the list to be displayed.

**Comment by JackDamei** [comment]
Sorry I wasn't clear enough about what I wanted to say.

I thought that the part where the list is updated should be outside of the
if/else statement. (I told about a removal of the else because no
instruction is inside anymore after that)

Because when the list is empty, the list is reset but no word is picked.
That leads to a round where a point is counted but no new word is shown.

The idea is :
If the list is empty :
  Reset the list AND pick a word
Else
  Just pick a word

=> a word is picked on every case

Sorry for the inconvenience

Best regards,
Jack Damei
