### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by halnader** [google-developer-training/android-kotlin-fundamentals-apps#446]
**Name of the Codelab or Codelab URL**
[Android Kotlin Fundamentals: Interacting with RecyclerView items](https://codelabs.developers.google.com/codelabs/kotlin-android-training-interacting-with-items/index.html?index=..%2F..android-kotlin-fundamentals#0)

**Describe the problem**
A clear and concise description of what the problem is.

Instruction at end of Step 2 suggests cleaning and rebuilding project however project will not build at that point before next step (Step 3) is complete.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Lesson:
-7.4 Interacting with RecyclerView items
Step: 
-4. Task: Make items clickable 
--Step 2: Pass the click listener to the view holder and the binding object

**How to reproduce?**
What are the exact steps to reproduce the problem?

Follow through code lab up to Step 2 in Task 4 and try to build.

**Versions**
1. What version of Android Studio are you using?
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: org.jetbrains.kotlin, com.google.services.firebase
2. What API level are you targeting?
defaultConfig {
        applicationId "com.example.android.trackmysleepqualityrecyclerview"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

**Additional information**

No issue in code, just issue in instruction order.

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@halnader 
Thank you for reaching out to us.
The reason we ask you to build the project is so that binding object is generated, not for running the app. 
The instructions to Run the app is in Step 3.
