### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by makirill** [google-developer-training/android-kotlin-fundamentals-apps#447]
**Name of the Codelab or Codelab URL**
Android Kotlin Fundamentals

**Describe the problem**
A clear and concise description of what the problem is.
Many pages having formatting problems especially where lists combined with images or other formatting. Looks like new version of the codelab site was deployed last weekend and probably this can be a reason why formatting was broken.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Bellow are URLs on the lessons, formatting problems can be seen in many places. I have not checked yet further lessons

https://codelabs.developers.google.com/codelabs/kotlin-android-training-get-started/#2
https://codelabs.developers.google.com/codelabs/kotlin-android-training-get-started/#3
https://codelabs.developers.google.com/codelabs/kotlin-android-training-get-started/#4
https://codelabs.developers.google.com/codelabs/kotlin-android-training-get-started/#5
https://codelabs.developers.google.com/codelabs/kotlin-android-training-app-anatomy/#2
https://codelabs.developers.google.com/codelabs/kotlin-android-training-images-compat/#2
https://codelabs.developers.google.com/codelabs/kotlin-android-training-images-compat/#4

**How to reproduce?**
What are the exact steps to reproduce the problem?

I can see problems with the text formatting using Firefox 81 and Chrome 86 on Ubuntu (18.04 and 20.04) and Windows 10 

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@makirill 
Thank you for reaching out to us.
Yes this is a known issue and we are still working on it. This should be fixed soon.

**Comment by jtavva** [comment]
@makirill 
Thank you for reaching out to us.
This should be fixed now.
