### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by zackhamin** [google-developer-training/android-kotlin-fundamentals-apps#448]
**Name of the Codelab or Codelab URL**

https://codelabs.developers.google.com/codelabs/kotlin-android-training-complex-lifecycle/index.html#3

**Describe the problem**
A clear and concise description of what the problem is.

After implementing the LifecycleObserver the app stops compiling with the following error;

``lateinit property runnable has not been initialized`

**In which lesson and step of the codelab can this issue be found?**

Lesson 4, 4. Task: Use the Android lifecycle library
**How to reproduce?**

What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using? Latest
2. What API level are you targeting? 30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@zackhamin 
Please provide us with your complete code in `DessertTimer.kt` file.
