### ISSUE TITLE
Android Kotlin Fundamentals codelab: typo

### ISSUE THREAD

**Issue by fvalela1** [google-developer-training/android-kotlin-fundamentals-apps#449]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-images-compat/#10

**Describe the problem**
Under `Question 2`, the question includes `xmx` at the end of the line.

**In which lesson and step of the codelab can this issue be found?**
01.3: Image resources and compatibility - step 11

**How to reproduce?**
Navigate to lesson + step.

**Versions**
n/a

**Additional information**
n/a

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@fvalela1 
Thank you so much for reporting this issue. This is fixed and will be published soon.
