### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by yobaba** [google-developer-training/android-kotlin-fundamentals-apps#450]
In the codelab kotlin-android-training-internet-filtering: Modify the call to getProperties() in the Retrofit service to pass along that filter query as a string
passing filter.value gave an error wrong type passed but passing filter.varargs solved the issue. I believe it must have been a typo error
_properties.value = MarsApi.retrofitService.getProperties(filter.varargs)

**Comment by jtavva** [comment]
@yobaba Thank you for reporting this issue.

Make sure you import `com.example.android.marsrealestate.network.MarsApiFilter`

Code for the complete method for your reference: 

```
    private fun getMarsRealEstateProperties(filter: MarsApiFilter) {
        viewModelScope.launch {
            _status.value = MarsApiStatus.LOADING
            try {
                _properties.value = MarsApi.retrofitService.getProperties(filter.value)
                _status.value = MarsApiStatus.DONE
            } catch (e: Exception) {
                _status.value = MarsApiStatus.ERROR
                _properties.value = ArrayList()
            }
        }
    }
```
Also please check your gradle files and make sure that you are using the latest version of the libraries.
