### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by git-rox1337** [google-developer-training/android-kotlin-fundamentals-apps#452]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-data-binding-basics/index.html#2

**Describe the problem**
Maybe it is not a problem - until 5th step of first task in this lesson, there is everything clear. But then when you wrote Kotlinize the function using .apply(), there is no explanation what means "Kotlinize", where to put this function, and all of a sudden binding expressions are gone in the code lines. Feels like there is some part of this course missing or at least needs more explanation. 
I've inspected the solution code for that and the project works, but i feel it needs to be corrected a little bit. 

**In which lesson and step of the codelab can this issue be found?**
02.4 - step 4, ad.5
**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@git-rox1337 
Thank you so much for reporting this issue. This is fixed and will be published soon.

The apply{} function, executes a block of code on an object reference. In this code block the reference object is binding.
Reference documentation:  https://kotlinlang.org/docs/reference/scope-functions.html
