### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by fvalela1** [google-developer-training/android-kotlin-fundamentals-apps#453]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-coroutines-and-room#5

**Describe the problem**
`clear()` function isn't private, but should be.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals: 6.2 Coroutines and Room - Step 6

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@fvalela1 
Thank you so much for reporting this issue. This is fixed and will be published soon.
PR: https://github.com/google-developer-training/android-kotlin-fundamentals-apps/pull/465
