### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by AironGomes** [google-developer-training/android-kotlin-fundamentals-apps#454]
**Name of the Codelab or Codelab URL**
Add user interactivity
https://codelabs.developers.google.com/codelabs/kotlin-android-training-interactivity/index.html#3

**Describe the problem**
Formating error with the text.
The images are very big too.
The numbering is not separated by paragraph.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@AironGomes 
Thank you so much for reporting this issue. This is fixed and will be published soon.
