### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by GraytApps** [google-developer-training/android-kotlin-fundamentals-apps#458]
**Name of the Codelab or Codelab URL**
Android Kotlin Fundamentals: Interacting with RecyclerView items

**Describe the problem**
The function onSleepNightClicked() is not spelled correctly. It is missing a "t" and reads: onSleepNighClicked()

**In which lesson and step of the codelab can this issue be found?**
Lesson number 5, step number 7 .

**How to reproduce?**
n/a

**Versions**
n/a

**Additional information**
n/a

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@GraytApps 
Thank you so much for reporting this issue. This is fixed and will be published soon.
