### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by JoaoWitorFelipe** [google-developer-training/android-kotlin-fundamentals-apps#459]
https://codelabs.developers.google.com/codelabs/kotlin-android-training-linear-layout/index.html?index=..%2F..android-kotlin-fundamentals#4

**Describe the problem**
To support older versions than API 17 (project specifies 16) you must also specify gravity or layout_gravity="center_horizontal"

**In which lesson and step of the codelab can this issue be found?**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-linear-layout/index.html?index=..%2F..android-kotlin-fundamentals#4

**How to reproduce?**
Only put the property android:textAlignment in TextView

**Versions**
Android Studio 4.0.1
API level 29

**Additional information**
![Screenshot_20201104_200449](https://user-images.githubusercontent.com/42946342/98177262-01b04d80-1ed9-11eb-8138-62ead26b8a13.png)

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@JoaoWitorFelipe 
Thank you so much for reporting this issue. 
The Minimum API level  mentioned in the codelab is API 19: Android 4.4 (KitKat) not API 16. 
Refer: https://codelabs.developers.google.com/codelabs/kotlin-android-training-linear-layout/index.html?index=..%2F..android-kotlin-fundamentals#2 > stetp 5
