### ISSUE TITLE
Android Kotlin Fundamentals codelab: 5.1 ViewModel: requireArguments() instead of arguments!!

### ISSUE THREAD

**Issue by vgoetz** [google-developer-training/android-kotlin-fundamentals-apps#460]
**Name of the Codelab or Codelab URL**
Android Kotlin Fundamentals: 5.1 ViewModel
https://codelabs.developers.google.com/codelabs/kotlin-android-training-view-model/index.html?index=..%2F..android-kotlin-fundamentals#7

**Describe the problem**
wrong variable

**In which lesson and step of the codelab can this issue be found?**
- 5.1 ViewModel
-- 8. Task: Use a ViewModelFactory
--- _Step_ 8.) "_In ScoreFragment, inside OnCreateView(), after [..]_
`viewModelFactory = ScoreViewModelFactory(ScoreFragmentArgs.fromBundle(arguments!!).score)`"

**How to reproduce and solve the problem?**
`arguments!!` can't be resolved.
Replace **`arguments!!`** with **`requireArguments()`**
Result:
`viewModelFactory = ScoreViewModelFactory(ScoreFragmentArgs.fromBundle(requireArguments()).score)`

**Versions**
1. What version of Android Studio are you using? --> 4.1
2. What API level are you targeting? --> 30

**Comment by jtavva** [comment]
@vgoetz 
Thank you so much for reporting this issue. This is fixed and will be published soon.
PR: https://github.com/google-developer-training/android-kotlin-fundamentals-apps/pull/464
