### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by TerryQuiet** [google-developer-training/android-kotlin-fundamentals-apps#462]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-constraint-layout/index.html#11

**Describe the problem**
 here

```
      R.id.red_button -> box_three_text.setBackgroundResource(R.color.my_red)
       R.id.yellow_button -> box_four_text.setBackgroundResource(R.color.my_yellow)
       R.id.green_button -> box_five_text.setBackgroundResource(R.color.my_green)
```

we're using : import kotlinx.android.synthetic.main.activity_main.*
while previously we used only findViewById. 
Maybe I'm missing synthetic mention in lessons. And Android Studio doesn't tell to import it.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals: 02.3 ConstraintLayout using the Layout Editor
12. Task: Add click handlers to the buttons

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
4.1
2. What API level are you targeting?
30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by fluffybunny074** [comment]
Place this in the setListeners()

 val redButton = findViewById<Button>(R.id.red_button)
            redButton.setOnClickListener {
                boxThreeText.setBackgroundResource(R.color.my_red)
            }
        val greenButton = findViewById<Button>(R.id.green_button)
            greenButton.setOnClickListener {
                boxFourText.setBackgroundResource(R.color.my_green)
            }
        val yellowButton = findViewById<Button>(R.id.yellow_button)
            yellowButton.setOnClickListener {
                boxFiveText.setBackgroundResource(R.color.my_yellow)
            }


You can then remove red/yellow/green buttons from makeColored() and also clickableViews in setListeners.
Sure there is a better way, but it works... and yes Data Bindings solves this

**Comment by Vikscripts** [comment]
As noted by fluffybunny074 , Data Binding is the most efficient solution for large apps.

An alternative for simple apps like this code lab is to change two lines of code as follows:
1 -  In "private fun setListeners()" function, pass three more parameters in the 'for' loop.

`        for (item in clickableViews) {
            item.setOnClickListener { makeColored(it, boxThreeText, boxFourText, boxFiveText ) }
        }`

2 -  Add local variable parameters to "private fun makeColored" as follows:
 
`private fun makeColored(view: View, box_three_text: View, box_four_text: View, box_five_text: View) {`
