### ISSUE TITLE
Android Kotlin Fundamentals codelab: link to depracated documentation

### ISSUE THREAD

**Issue by savvasenok** [google-developer-training/android-kotlin-fundamentals-apps#463]
https://codelabs.developers.google.com/codelabs/kotlin-android-training-complex-lifecycle/index.html#3

**Describe the problem**
Link leads to deprecated documentation

**In which lesson and step of the codelab can this issue be found?**
Lesson 4 + step 4 + substep 1 + point 4

**How to reproduce?**
Visit the page

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@savvasenok 
Updated the documentation link to https://developer.android.com/reference/androidx/lifecycle/Lifecycle.Event
Thank you so much for reporting this issue. This is fixed and will be published soon.
