### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by vicentecarloscisnerosolivo** [google-developer-training/android-kotlin-fundamentals-apps#467]
**https://codelabs.developers.google.com/codelabs/kotlin-android-training-complex-lifecycle/index.html#0**

**onCreate(savedInstanceState: Bundle?)**
In the codelab of Complex Lifecycle Situations, when I kill the process of the bundle, the propiertie savedInstanceState is always null, in my virtual device, the virtual device has Android 10.0

**In which lesson and step of the codelab can this issue be found?**
Complex Lifecycle Situations, lessson 5, step 5
Lesson number + step number.

**How to reproduce?**
following the steps of the codelab, also rotating the device

**Versions**
1.Android Studio Version: 4.0.1
2. What API level are you targeting? 30

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@vicentecarloscisnerosolivo 
Thank you so much for reporting this issue. This is fixed and will be published soon.

To simulate the app termination, please follow the following steps

1. Compile and run the app.
2. Stop the app by selecting Run > Stop ‘app’ from the menu. Now the app is installed on your device/emulator but the app is not running.
3. Open app launcher in your device/emulator and select Dessert Clicker app. 
4. Press the cupcake at least five times until it switches to a donut. Click Home to put the app into the background.
5. In the Android Studio Terminal tab, run adb to shut down the app's process. 

`adb shell am kill com.example.android.dessertclicker
`
6. Use the recents screen to return to the app.
