### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by stevenshapiro** [google-developer-training/android-kotlin-fundamentals-apps#468]
**Name of the Codelab or Codelab URL**
Android Kotlin Fundamentals: 02.3 ConstraintLayout using the Layout Editor

**Describe the problem**
In the function below, box_three_text, etc. are not defined.  They were only defined in the setListeners() function.

private fun makeColored(view: View) {
   when (view.id) {

      ...

       // Boxes using custom colors for background
       R.id.red_button -> box_three_text.setBackgroundResource(R.color.my_red)
       R.id.yellow_button -> box_four_text.setBackgroundResource(R.color.my_yellow)
       R.id.green_button -> box_five_text.setBackgroundResource(R.color.my_green)

       else -> view.setBackgroundColor(Color.LTGRAY)
   }
}

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals: 02.3 ConstraintLayout using the Layout Editor
12. Task: Add click handlers to the buttons

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
N/A

2. What API level are you targeting?
N/A

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
Similar to #313
