### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by everlucky** [google-developer-training/android-kotlin-fundamentals-apps#470]
**Name of the Codelab or Codelab URL**

https://codelabs.developers.google.com/codelabs/kotlin-android-training-app-anatomy/#7
**Describe the problem**
A clear and concise description of what the problem is.
String resources are contained in the **values/res/string.xml** file. ===> Should be **res/values/strings.xml**
**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Android Kotlin Fundamentals 01.2: Anatomy of Basic Android Project + 8. Summary
**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@everlucky 
Thank you so much for reporting this issue. This is fixed and will be published soon.
