### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by LioisSAD** [google-developer-training/android-kotlin-fundamentals-apps#471]
**Name of the Codelab and Codelab URL**
**Android Kotlin Fundamentals:** LinearLayout using the Layout Editor
6
https://codelabs.developers.google.com/codelabs/kotlin-android-training-linear-layout/index.html?index=..%2F..android-kotlin-fundamentals#5

**Describe the problem**
**marginTop** not metioned

**In which lesson and step of the codelab can this issue be found?**
Lesson 2: Layouts -> Step 6: Style your TextView.

**Additional information**
Less relevant typo: quotation marks and description don't match across the padding and margin sections.
Anyway would be nice to mention marginTop

**codelab:** android-kotlin-fundamentals

![image](https://user-images.githubusercontent.com/16020653/99450833-9c6d4b00-2921-11eb-8129-994b190d33e2.png)

**Comment by jtavva** [comment]
@LioisSAD 
Thank you for reporting!
`android:layout_marginTop` is added in the description. 
This is fixed and will be published soon.
