### ISSUE TITLE
Android Kotlin Fundamentals codelab: 7.2, task 7

### ISSUE THREAD

**Issue by fdbozzo** [google-developer-training/android-kotlin-fundamentals-apps#473]
**Name of the Codelab or Codelab URL**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-diffutil-databinding/#6

**Describe the problem**
Step 1.3 says:
"In the sleeptracker package, create and open a file called BindingUtils.kt"

The lesson says nothing about the type of file to make (class, object, etc), so one naturally makes a class with the anotated methods with @BindingAdapter, but this doesn't work and throw an error at the end with the message:
"Required DataBindingComponent is null in class ListItemSleepNightBindingImpl"

**The solution**, found on Internet, is changing the statement "**class** BindingUtils" to "**object** BindingUtils", and anotating every method with **@JvmStatic**

**In which lesson and step of the codelab can this issue be found?**
Lesson number 7.2 + Task 7 + step 1.3 until the end of the page

**How to reproduce?**
Follow Codelabs in sequence, starting with the code of lesson 7.1 step 4.1, which says to download this code:
https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/tree/master/RecyclerViewFundamentals-Starter

**Versions**
1. What version of Android Studio are you using? 4.2 Canary 16
2. What API level are you targeting? 30

**Additional information**
The code that some Codelabs do step by step is not always what the Codelab expect in future steps, and following all in sequence makes code that is incomplete, which makes difficult  to continue de exercise.

**codelab:** android-kotlin-fundamentals

**Comment by Karimi1381** [comment]
That's Great!
Thank you for share this solution
