### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by t1eap** [google-developer-training/android-kotlin-fundamentals-apps#484]
**Name of the Codelab or Codelab URL**
Android Kotlin Fundamentals: 6.2 Coroutines and Room and/or 6.1 Create a Room Database
https://developer.android.com/codelabs/kotlin-android-training-coroutines-and-room#6
https://developer.android.com/codelabs/kotlin-android-training-room-database#5

**Describe the problem**
I'm new to android, so perhaps I'm overlooking something or perhaps I missed a step in the module.  With that said:
At the start of the module (6.2), you have the option of continuing with the code from 6.1 or downloading the starter code.  I elected to continue.
After completing the module, I was receiving an error due to the line `sleepDao.insert(night)` in the SleepDatabaseTest file which states "Suspend function 'insert' should be called only from a coroutine or another suspend function".  I did not see any references in the 6.2 module explaining that this file is expected to have an error and that it can be ignored.
If I attempt to correct the error with adding `suspend` to `fun insertAndGetNight() {` (what android studio recommends), the test would return a failed test.  Note that the test is called out to execute if building the app (i.e. it's listed in the Run -> Edit Configurations).
After reviewing the solution code for 6.2 I noticed that the app build.gradle does not contain the test dependencies present in 6.1 nor is there an "Android Instrumented Tests" defined in Run -> Edit Configurations...  despite there being the presence of the SleepDatabaseTest file (it appears the file is included in the solution code, despite never being used which seems unusual to me).
If you add the dependencies back in to the 6.2 solution code from the 6.1 code, the SleepDatabaseTest file will have the same errors present as if continuing 6.2 with the code 6.1 one generated (versus using 6.2 starter code).

**In which lesson and step of the codelab can this issue be found?**
It seems like there is a missing step in 6.1 that is to disable the test script prior to showing the solution code.  Or, perhaps 6.1's starter code should never call it out as an Android Instrumentation Test (assuming it's possible to run it manually for the module without this).
It might be nice to explain why the test code no longer applies and/or works in 6.2.

**How to reproduce?**
Complete Module 6.1 using the 6.1 starter app.  Notice the differences from the 6.1 completion code to the 6.2 starter code (no android instrumentation test present in the starter code, no test dependencies). Try to complete 6.2 with the code from a completed 6.1 module and you will run into an error because the test code from 6.1 is still being executed and it is running into errors now that coroutines are implemented.

**Versions**
1. What version of Android Studio are you using?
4.1.1
2. What API level are you targeting?
30

**Additional information**
N/A

**codelab:** android-kotlin-fundamentals

**Comment by stvreumi** [comment]
I also encounter this problem. After I change the app configuration from test to app, it works.
