### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by someoneEsle** [google-developer-training/android-kotlin-fundamentals-apps#49]
**Describe the problem**
Screenshot says "Vertial" instead of "Vertical"

**In which lesson and step of the codelab can this issue be found?**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-linear-layout/index.html#3

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment]
Thanks for the report. Fixed.
