### ISSUE TITLE
2.4 Data binding basics: Specify directory java/com/example/android/aboutme

### ISSUE THREAD

**Issue by denpo1022** [google-developer-training/android-kotlin-fundamentals-apps#50]
**Describe the problem**
Wrong description of target folder when declaring a new kotlin file `MyName.kt`.

**In which lesson and step of the codelab can this issue be found?**
02.4: Data-binding basics - 4. Task: Use data binding to display data - Step 1: Create the MyName data class

**How to reproduce?**
![註解 2020-02-21 213937](https://user-images.githubusercontent.com/30108508/75044591-ddecd900-54fc-11ea-9421-7d762d2fcf8d.png)

**Versions**
1. 3.5.3
2. 23

**Additional information**
No

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Thanks, we can clarify so instead of "java", we can say "java/com/example/android/aboutme"
