### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by proticjana** [google-developer-training/android-kotlin-fundamentals-apps#52]
**Describe the problem**
Type mismatch: inferred type is Int but Drawable! was expected
![image](https://user-images.githubusercontent.com/11773304/75364723-74821700-58bc-11ea-9228-6dbde2ba3242.png)

**In which lesson and step of the codelab can this issue be found?**
lesson 01.3 : step 5

**How to reproduce?**
Just following the steps.

**Versions**
1. Android Studio 3.5.3
2. API 28

**Additional information**
Solution: using diceImage.setImageDrawable(resources.getDrawable(drawableResource, applicationContext.theme))

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
You can call diceImage.setImageResource() with the resource ID.

      val drawableResource = when (randomInt) {
            1 -> R.drawable.dice_1
            2 -> R.drawable.dice_2
            3 -> R.drawable.dice_3
            4 -> R.drawable.dice_4
            5 -> R.drawable.dice_5
            else -> R.drawable.dice_6
        }

        diceImage.setImageResource(drawableResource)

Solution code: https://github.com/google-developer-training/android-kotlin-fundamentals-apps/blob/master/DiceRollerFinal/app/src/main/java/com/example/android/diceroller/MainActivity.kt
