### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by duri0214** [google-developer-training/android-kotlin-fundamentals-apps#54]
**Describe the problem**
'View attributes' section: 

> The android:layout_width and android:layout_height attributes indicate the weight and height of a view.

weight is width ??

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Android Kotlin Fundamentals 01.2: Basic app anatomy
https://codelabs.developers.google.com/codelabs/kotlin-android-training-app-anatomy/#7

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
3.5
2. What API level are you targeting?
29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Fixed now, thanks!
