### ISSUE TITLE
Android Kotlin Fundamentals codelab: Getting data from the internet

### ISSUE THREAD

**Issue by krohak** [google-developer-training/android-kotlin-fundamentals-apps#552]
**Name of the Codelab or Codelab URL**
Getting data from the internet
https://developer.android.com/codelabs/kotlin-android-training-internet-data?index=..%2F..android-kotlin-fundamentals#4

**Describe the problem**
_A clear and concise description of what the problem is._
@Json(name = "img_src") decorator of Moshi is not parsing correctly

**In which lesson and step of the codelab can this issue be found?**
_Lesson number + step number._
5. Task: Parse the JSON response with Moshi
Step 2: Implement the MarsProperty data class

**How to reproduce?**
_What are the exact steps to reproduce the problem?_
Try printing out the parsed json, the imageSrcUrl will be null

**Versions**
1. What version of Android Studio are you using?
4.1.1

2. What API level are you targeting?
30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by wrimicha** [comment]
Try using @field:Json ? seems to work when I do it this way
