### ISSUE TITLE
Android Kotlin Fundamentals codelab: MarsRealestate Error

### ISSUE THREAD

**Issue by wrimicha** [google-developer-training/android-kotlin-fundamentals-apps#553]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-internet-images/#2

**Describe the problem**
A clear and concise description of what the problem is.

In step 2 part 1, we are told to label the live data and mutable live data to 'property'. We are later told to access it in the getMarsRelestateProperties() as 'properties.value'. It is unclear whether the live data values should be a list of MarsProperty objects or just a MarsProperty object, because setting them to a single object provides a type mismatch in the try block of getMarsRelestateProperties().

Additionally, following the steps provided in this codelab, in Step 2, part 4 we are not able to get access the viewModel.prtoperty.imgSrcUrl property through databinding.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

Step 2,  1-5

**How to reproduce?**
What are the exact steps to reproduce the problem?
Just follow the steps provided up to Step 2 of this code lab

**Versions**
1. What version of Android Studio are you using? 4.1.1
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by francas** [comment]
I'm also interested in a solution as the current steps don't build with `unresolved reference` errors
