### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by HashimJVZ** [google-developer-training/android-kotlin-fundamentals-apps#560]
**02.3 ConstraintLayout using the Layout Editor**

**Unresolved reference of buttons**

**In which lesson and step of the codelab can this issue be found?**
Lesson number 3 step number 4.

**How to reproduce?**
Copy the exact content of the step.
![problem](https://user-images.githubusercontent.com/43889022/105185228-481b5d00-5b56-11eb-8bc2-b24c57f9f7de.png)

**Versions**
1. What version of Android Studio are you using?
    4.1.2
2. What API level are you targeting?
    30

**codelab:** android-kotlin-fundamentals

**Comment by gavvvel** [comment]
The function makeColored does not have those three boxes in their scope, since they are not passed down nor declared globally.

You can either initiate them globally or get the views in those lines like:
`      R.id.red_button -> box_three_text.setBackgroundResource(R.color.my_red)
       R.id.yellow_button -> box_four_text.setBackgroundResource(R.color.my_yellow)
       R.id.green_button -> box_five_text.setBackgroundResource(R.color.my_green)
`
