### ISSUE TITLE
Android Kotlin Fundamentals codelab: course content overlaps with the Basics course

### ISSUE THREAD

**Issue by nivivier** [google-developer-training/android-kotlin-fundamentals-apps#567]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-welcome?index=..%2F..android-kotlin-fundamentals#1

**Describe the problem**
This courses has to be refactored, to stop overlapping with the "Basics" course and give a consistent learning experience

**In which lesson and step of the codelab can this issue be found?**
These 6 pathways :
- Pathway 1: Build your first app
- Pathway 2: Build an Interactive App
- Pathway 3: Layouts
- Pathway 4: Navigation
- Pathway 5: Activity and fragment lifecycles
- Pathway 6: Architecture components
Are basically duplicates of the Unit 1, 2 and 3 from the Basics course.

**How to reproduce?**
Go to  https://developer.android.com/codelabs/kotlin-android-training-welcome?index=..%2F..android-kotlin-fundamentals#1
Read "What the course covers"
Compare with https://developer.android.com/courses/android-basics-kotlin/course

**codelab:** android-kotlin-fundamentals

**Comment by jkcoolmom** [comment]
Thanks for your feedback!
