### ISSUE TITLE
Kotlin Android Fundamentals: Styles and themes - GDGFinderFinal app is crashing

### ISSUE THREAD

**Issue by SudKul** [google-developer-training/android-kotlin-fundamentals-apps#574]
**Name of the Codelab or Codelab URL**
[Kotlin Android Fundamentals: Styles and themes](https://developer.android.com/codelabs/kotlin-android-training-styles-and-themes?index=..%2F..android-kotlin-fundamentals#6)

**Describe the problem**
The GDGFinderFinal app is crashing when clicking on the FAB, generating the following exception:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.gdgfinder, PID: 21069
    retrofit2.HttpException: HTTP 404 Not Found
        at com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory$BodyCallAdapter$adapt$2.onResponse(CoroutineCallAdapterFactory.kt:104)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
I/Process: Sending signal. PID: 21069 SIG: 9
```

**Possible reason for crashing** 
In the [GdgApiService.kt](https://github.com/google-developer-training/android-kotlin-fundamentals-apps/blob/master/GDGFinderFinal/app/src/main/java/com/example/android/gdgfinder/network/GdgApiService.kt) file, the `@GET("gdg-directory.json")` is not getting resolved at the `BASE_URL = "https://android-kotlin-fun-mars-server.appspot.com/"`. 

**In which lesson and step of the codelab can this issue be found?**
[Lesson 10: Designing for everyone + Step 7. Solution code](https://developer.android.com/codelabs/kotlin-android-training-styles-and-themes?index=..%2F..android-kotlin-fundamentals#6)

**How to reproduce?**
Run the GDGFinderFinal app, and click either on the **FAB** or the **Menu --> GDG Search**. It will momentarily show a new screen saying *"Waiting for location and network result"*, and then crashes. 

**Versions**
1. Android Studio 4.0.1
2. API 30

**Additional information**
NIL

**codelab:** android-kotlin-fundamentals

@jtavva Can you look into this? Thanks in advance.

**Comment by jtavva** [comment]
@SudKul 
Thank you for reaching out to us.
This should be fixed now.

Note: Please create a new emulator when you are testing this issue.

**Comment by SudKul** [comment]
Thank you @jtavva for such a quick turnaround. I appreciate your efforts.
