### ISSUE TITLE
Android Kotlin Fundamentals codelab: 03.2 Define navigation paths

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-kotlin-fundamentals-apps#578]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-add-navigation/index.html#7

**Describe the problem**
The link titled "Designing Back and Up navigation" leads to the "Design navigation graphs" page, the latter of which seems more appropriate for the name of the link.

**In which lesson and step of the codelab can this issue be found?**
8. Task: Add an Up button in the app bar

**How to reproduce?**
As stated above, it's an issue of the name of the link.

**Versions**
Not applicable.

**Additional information**
Nil.

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@jhs-tw 
Thank you for reaching out to us.
Would you be able to provide us with a screenshot?

**Comment by jhs-tw** [comment]
> @jhs-tw
> Thank you for reaching out to us.
> Would you be able to provide us with a screenshot?

A screen recording is uploaded as below.

https://user-images.githubusercontent.com/42627483/109739460-99fadc80-7c04-11eb-8ef6-5554dffd07c4.mp4
