### ISSUE TITLE
Provide enough Pictures for the beginners so that it will be more easier to follow those steps

### ISSUE THREAD

**Issue by Sheriman** [google-developer-training/android-kotlin-fundamentals-apps#582]
Provide enough pictures or video for us sometimes I got confuse.  Shows us some illustrations to what you are explaining most especially getting started with building TV App. That code lab has really frustrated my work.
we need enough pictures to fully understand those steps we need to take to build our android App.
Thank you Google

**Comment by jtavva** [comment]
@Sheriman 
Thank you for reaching out to us.
I think you reported the issue in the wrong forum. This Github repository is for Android Kotlin Fundamentals.
