### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by kelvs-ricafort** [google-developer-training/android-kotlin-fundamentals-apps#587]
Android Kotlin Fundamentals 8.1 : Getting data from internet

**Describe the problem**
I think server is dead

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
4. Task Connect to a web service with Retrofit

**How to reproduce?**
What are the exact steps to reproduce the problem?
Unable to resolve host "android-kotlin-fun-mars-server.appspot.com". No address associated with hostname

**Versions**
1. What version of Android Studio are you using? Android Studio 4.1.2
2. What API level are you targeting? 30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by Cizawells** [comment]
Hi click on the link to follow the codelab from start
https://developer.android.com/codelabs/kotlin-android-training-internet-data?index=..%2F..android-kotlin-fundamentals#0

**Comment by kelvs-ricafort** [comment]
![dead_server](https://user-images.githubusercontent.com/60914571/108810408-09117900-75e6-11eb-816e-e09c307a4946.PNG)
![dead_server-cmd](https://user-images.githubusercontent.com/60914571/108810414-0ca50000-75e6-11eb-8348-241e29d1adc5.PNG)

**Comment by Cizawells** [comment]
Got it, thanks!

**Comment by kelvs-ricafort** [comment]
any update @Cizawells?

**Comment by kelvs-ricafort** [comment]
any alternative server pls?

**Comment by jtavva** [comment]
@Cizawells 
Thank you for reaching out to us.
Server seems to be working properly. 
https://android-kotlin-fun-mars-server.appspot.com/realestate
Issue could be from your end.

**Comment by killerfish16** [comment]
@kelvs-ricafort In ping, please remove the protocol then it should work.
![image](https://user-images.githubusercontent.com/40337600/143136548-bf7235e1-fe68-4043-b323-c8de7960ba70.png)

@Shobaky, Please check the following -- the base url shouldn't have a slash at the end.

private const val BASE_URL =
    "https://android-kotlin-fun-mars-server.appspot.com" -- this works fine.

private const val BASE_URL =
    "https://android-kotlin-fun-mars-server.appspot.com/" -- this won't work and will throw the following error
Unable to resolve host "android-kotlin-fun-mars-server.appspot.com": No address associated with hostname
