### ISSUE TITLE
Android Kotlin Fundamentals codelab: Lesson 8: Connecting to the internet

### ISSUE THREAD

**Issue by sdidier-dev** [google-developer-training/android-kotlin-fundamentals-apps#588]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-internet-data?index=..%2F..android-kotlin-fundamentals#3

**Describe the problem**
Not a big deal for the codelab, but I think in the JSON data from the server, the 'rent' an 'buy' type are inverted.
Ie: 
first property: {"price":450000,"id":"424905","type":"buy"
second property: {"price":8000000,"id":"424906","type":"rent"

it is more expensive per month than bying a property :)

**codelab:** android-kotlin-fundamentals

**Comment by kelvs-ricafort** [comment]
cannot connect to server

**Comment by jtavva** [comment]
@sdidier-dev 
Thank you for reaching out to us.
This JSON is provided by the NASA, so I don't think we can change any property values, but thank you for reporting.
