### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by c-ggr** [google-developer-training/android-kotlin-fundamentals-apps#590]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-interactivity/index.html#6

**Describe the problem**

**In which lesson and step of the codelab can this issue be found?**
7. Task: Add a click listener to the DONE button
Step 1: Add a click listener

**How to reproduce?**
Wrong: nicknameTextView.text = editText.text
Correct: nicknameTextView.text = editText.text.toString()

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment]
@c-ggr 
Could you please provide more information about the error you are getting?

**Comment by c-ggr** [comment]
With "toString" removes the underline in the TextView
