### ISSUE TITLE
Android Kotlin Fundamentals codelab: Lifecycles and logging missing step "Next Codelab"

### ISSUE THREAD

**Issue by PitchBlack07** [google-developer-training/android-kotlin-fundamentals-apps#618]
**Name of the Codelab or Codelab URL**

**Describe the problem**
The "Android Kotlin Fundamentals: Lifecycles and logging" codelab is missing the step "Next Codelab". This step was included in the previous codelabs (lessons 1-3)

I find that to be confusing, especially because step 5 mentioned that a problem in the sample app will be fixed in a future codelab. As step 5 does not mention in which "future codelab" this will be solved, I assume that it should have been in lesson 4. But alas, it is missing there.

**In which lesson and step of the codelab can this issue be found?**
Lesson 4, Step 5

**How to reproduce?**
Navigate to https://developer.android.com/codelabs/kotlin-android-training-lifecycles-logging and observe that the menu to the left is missing the menu item "Next Codelab"

**Versions**
N/A

**Additional information**
N/A

**codelab:** android-kotlin-fundamentals

**Comment by Rafael-Caseiro** [comment]
Still having this issue
