### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by brian-richey** [google-developer-training/android-kotlin-fundamentals-apps#678]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-quality-and-states?authuser=1#3

**Describe the problem**
Program won't compile---multiple Unresolved references
----SleepTrackerFragmentDirections
----SleepQualityFragmentArgs
----sleepqualityFragmentDirections

**In which lesson and step of the codelab can this issue be found?**
Lesson #4 - Step #2

**How to reproduce?**

Enter code exactly as presented in Codelab

**Versions**
1. What version of Android Studio are you using? 4.2.1
2. What API level are you targeting? 30
[SleepNight.zip](https://github.com/google-developer-training/android-kotlin-fundamentals-apps/files/6647415/SleepNight.zip)
[SleepQualityFragment.zip](https://github.com/google-developer-training/android-kotlin-fundamentals-
[navigation.zip](https://github.com/google-developer-training/android-kotlin-fundamentals-apps/files/6647663/navigation.zip)
loper-training/android-kotlin-fundamentals-apps/files/6647655/SleepTrackerFragment.zip)

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by stefanhk31** [comment]
+1

**Comment by WonJoongLee** [comment]
You can solve the problem with changing the `navigationVersion` in the project build.gradle file. I found that it works from the version `1.0.0`. So you should change it like
### From
```
navigationVersion = '1.0.0-alpha08'
```
### To
```
navigationVersion = '1.0.0'
```
Then there won't be problem with `SleepTrackerFragmentDirections`.
