### ISSUE TITLE
6.2 Variable name night

### ISSUE THREAD

**Issue by bpc6** [google-developer-training/android-kotlin-fundamentals-apps#68]
**Describe the problem**
Reference to night should be oldNight

**In which lesson and step of the codelab can this issue be found?**
Lesson 6.2, Task 6, Step 4.2

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment]
Not sure if I understand the problem. It should be okay for the variable name to be night in the update() method. Is there a reason it should be oldNight?
