### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Generic-droid** [google-developer-training/android-kotlin-fundamentals-apps#727]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-constraint-layout#11

**Describe the problem**
// Boxes using custom colors for background
       R.id.red_button -> **box_three_text**.setBackgroundResource(R.color.my_red)
       R.id.yellow_button -> **box_four_text**.setBackgroundResource(R.color.my_yellow)
       R.id.green_button -> **box_five_text**.setBackgroundResource(R.color.my_green)

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals: 02.3 ConstraintLayout using the Layout Editor

**How to reproduce?**
Unresolved reference: **box_three_text**
Unresolved reference: **box_four_text**
Unresolved reference: **box_four_text**

**Versions**
1. What version of Android Studio are you using?
Arctic Fox | 2020.3.1 Patch 2
2. What API level are you targeting?
31

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by mst12** [comment]
I have the same problem

**Comment by maxmopp** [comment]
You are missing import kotlinx.android.synthetic.main.activity_main.* in main.kt
requires plugins {...     id 'kotlin-android-extensions'  ...  in build.gradle(:app) + sync now
[https://medium.com/android-ideas/findviewbyid-in-kotlin-ce4d22193c79](url)
[https://stackoverflow.com/questions/52271521/import-kotlinx-android-synthetic-main-activity-main-is-not-working](url)
