### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ghost** [google-developer-training/android-kotlin-fundamentals-apps#730]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-constraint-layout?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F%3Fcat%3Dandroid#11

**Describe the problem**
A clear and concise description of what the problem is.

this code given en de page is incorrect
// Boxes using custom colors for background
       R.id.red_button -> box_three_text.setBackgroundResource(R.color.my_red)
       R.id.yellow_button -> box_four_text.setBackgroundResource(R.color.my_yellow)
       R.id.green_button -> box_five_text.setBackgroundResource(R.color.my_green)
the app doesn't run by using it

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

lesson 02.3 ConstraintLayout using the Layout Editor
step 12

**How to reproduce?**
What are the exact steps to reproduce the problem?

    Inside the makeColored() function, add code to change the text views' colors when the user taps the buttons. Use the setBackgroundResource() function to set a custom color, defined in the resources as a view's background. Use the setBackgroundColor()function to set predefined colors as view's background Add the new code above the else statement, as shown:

**Versions**
1. What version of Android Studio are you using? Androis Studio 4.2.1
2. What API level are you targeting? 30

**Additional information**

**codelab:** android-kotlin-fundamentals

            R.id.red_button -> findViewById<TextView>(R.id.box_three_text).setBackgroundResource(R.color.my_red)
            R.id.yellow_button -> findViewById<TextView>(R.id.box_four_text).setBackgroundResource(R.color.my_yellow)
            R.id.green_button -> findViewById<TextView>(R.id.box_five_text).setBackgroundResource(R.color.my_green)

**Comment by S-Threepio** [comment]
Hi @Yanivag21 could you please check the solution code once and compare with your own code?
Perhaps checking the view id's might be helpful.
Let me know if this helps

**Comment by inuitviking** [comment]
In build.gradle (Module:***) above the `android` block, add this:
```gradle
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
```

Sync and you should be able to build.
This will result in a deprecation warning, but you'll learn about data binding in the next tutorial which basically fixes this issue.

See #804 where I go through the same issue.
