### ISSUE TITLE
Android Kotlin Fundamentals codelab: GuessTheWordViewModel

### ISSUE THREAD

**Issue by blueglyph** [google-developer-training/android-kotlin-fundamentals-apps#734]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-view-model?index=..%2F..android-kotlin-fundamentals#8

Suggestion: use view binding instead of data binding.

In your architecture guide (https://developer.android.com/topic/libraries/data-binding), you clearly state that " In many cases, view binding can provide the same benefits as data binding with simpler implementation and better performance. If you are using data binding primarily to replace findViewById() calls, consider using view binding instead."

This is exactly the case for this app, you are using dataBinding yet you manually set the text fields to their value (only the score and the word to display), at the expense of a longer code, longer compile time, and from what your website says, poorer performance when running on the device. So it doesn't show the good example.

**Comment by S-Threepio** [comment]
> Very funny.

what's funny?
