### ISSUE TITLE
7.1 Sleep tracker app crash on adapter.data = it

### ISSUE THREAD

**Issue by Patrick-Wallin** [google-developer-training/android-kotlin-fundamentals-apps#76]
**Describe the problem**
sleepTrackerViewModel.nights.observe(viewLifecycleOwner, Observer {
            it?.let {
                adapter.data = it
            }
        })
It crashed the app at the line of "adapter.data = it"

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
7.1, 5

**How to reproduce?**
My mistake... I had to remove ViewHolder.

 val view = layoutInflater
                .inflate(R.layout.list_item_sleep_night, parent, false) as ViewHolder

to 

 val view = layoutInflater
                .inflate(R.layout.list_item_sleep_night, parent, false)

**Comment by kkuan2011** [comment]
Hello Patrick! Is this still an issue in the codelab or were you able to resolve it in your code?
