### ISSUE TITLE
Android Kotlin Fundamentals codelab: I don't have onStart() method in my Android Studio. Any alternatives?

### ISSUE THREAD

**Issue by evoAkash** [google-developer-training/android-kotlin-fundamentals-apps#78]
**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by reknoZ** [comment]
Please answer the questions above, especially which Codelab you are doing when you get the error. I've followed the Codelab's from 01.1 to 04.1 and everything has worked, including the `onStart` code.

Did you add the functions as instructed?

Without precise, detailed information, no one will be able to help you resolve your issue.

**Comment by kkuan2011** [comment]
Unfortunately we'll need more information to debug the issue. You can open a new issue with the details filled out, thanks!
