### ISSUE TITLE
Android Kotlin Fundamentals: 03.2 Define navigation paths

### ISSUE THREAD

**Issue by vantaboard** [google-developer-training/android-kotlin-fundamentals-apps#802]
**[Android Kotlin Fundamentals: 03.2 Define navigation paths](https://developer.android.com/codelabs/kotlin-android-training-add-navigation?authuser=1)**

**Pop Behavior Image Incorrect**
the action for navigating from the `gameFragment` to the `gameWonFragment` should have the `popUpTo` attribute in pop behavior set to `gameFragment`, but the image shows

> ![image](https://user-images.githubusercontent.com/86866786/162588384-088dcd3a-2e22-4da4-9f19-bb95d7a7472f.png)

This is incorrect because just before the image, the documentation says to

> set `popUpTo` to `gameFragment` in the Attributes pane.

**codelab:** android-kotlin-fundamentals

**Comment by titan472** [comment]
Rewrite the platform in c++ and run it in gtx mode or ad-hoc play. Reset
the action pain for start and end code the tile to game over. Repaste the
end image and wiat to pixelste

**Comment by blackboardd** [comment]
> This is not helpful.

**Comment by lucioaguiar** [comment]
The image is still incorrect
