### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by abhineshchandra1234** [google-developer-training/android-kotlin-fundamentals-apps#803]
**https://developer.android.com/codelabs/kotlin-android-training-constraint-layout?authuser=1#11**

**Describe the problem**
Unknow reference to variables

**In which lesson and step of the codelab can this issue be found?**
[Android Kotlin Fundamentals: 02.3 ConstraintLayout using the Layout Editor](https://developer.android.com/codelabs/kotlin-android-training-constraint-layout?authuser=1) + 12

**How to reproduce?**
 R.id.red_button -> box_three_text.setBackgroundResource(R.color.my_red)
box_three_text has no reference in the calling method

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by inuitviking** [comment]
In build.gradle (Module:***) above the `android` block, add this:
```gradle
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
```

Sync and you should be able to build.
This will result in a deprecation warning, but you'll learn about data binding in the next tutorial which basically fixes this issue.
