### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by txs13** [google-developer-training/android-kotlin-fundamentals-apps#82]
**Describe the problem**
The typo in the lesson text item#6: "Change the vertical bias of the yellow_button to 100, to drop down the buttons to the bottom of the layout."
The correct value is 1.0 (as it is actually mentioned in the code below)

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 02.3: Constraint layout using the Layout Editor
Step #11

**How to reproduce?**
Correct the lesson web-page :)

**Versions**
1. Android Studio v 3.6.1 
2. Target API level 29

**Additional information**
---

**codelab:** android-kotlin-fundamentals

**Comment by reknoZ** [comment]
The value is different depending on whether you're in visual Design mode (0-100) or code-based XML mode (0.0-1.0).

If you look at the Attributes panel in Design mode, you'll see that the vertical bias is 100. If you look at the corresponding XML file, you'll see that it's 1.0.

There is no error in the Codelab.

**Comment by kkuan2011** [comment]
Yes the codelab now specifies both, so its either 100 in the Design view or 1.0 when editing XML directly.
