### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by gidiav** [google-developer-training/android-kotlin-fundamentals-apps#822]
**Name of the Codelab or Codelab URL**
[Android Kotlin Fundamentals: 5.1 ViewModel](https://developer.android.com/codelabs/kotlin-android-training-view-model)

**Describe the problem**
Compiler errors
1. Error described [here](https://stackoverflow.com/questions/70992947) - can be resolved by using lifecycle library 2.4.1 instead of the latest one

2. Then, this error: Class 'ScoreViewModelFactory' is not abstract and does not implement abstract member public abstract fun <T : ViewModel> create(modelClass: Class<T>): T defined in androidx.lifecycle.ViewModelProvider.Factory

After looking closely I saw that the codelab has "fun <T : ViewModel?>" while the error says "fun <T : ViewModel>", i.e., without teh question mark.  After removing the question mark, it compiles.

**In which lesson and step of the codelab can this issue be found?**
Part 8 (Use a ViewModelFactory), step 6 

**How to reproduce?**
Follow all the steps in the codelab and compile

**Versions**
1. What version of Android Studio are you using?
4. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
