### ISSUE TITLE
Android Kotlin Fundamentals codelab: 02.4 Data Binding Fundamentals

### ISSUE THREAD

**Issue by paulwolt** [google-developer-training/android-kotlin-fundamentals-apps#823]
**Name of the Codelab or Codelab URL**
Android Kotlin Fundamentals codelab: 02.4 Data Binding Fundamentals
https://developer.android.com/codelabs/kotlin-android-training-data-binding-basics#3

**Describe the problem**
In MainActivity.kt, incomplete reference to MyName class element:
      `private val myName: MyName = MyName("Aleks Haecky")`
Into which field does "Aleks Haecky" go, name or nickname?
      `private val myName: MyName = MyName(name="Aleks Haecky")`

**In which lesson and step of the codelab can this issue be found?**
02.4, Task 4, Step 3. Also in github.

**How to reproduce?**
n/a

**Versions**
1. What version of Android Studio are you using? 2021.2.1
2. What API level are you targeting? n/a

**Additional information**
Struggling with numerous incompatibilities with newer version of Studio, but overall this tutorial is extraordinarily helpful.
Thanks so much. 

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
