### ISSUE TITLE
Android Kotlin Fundamentals codelab: Android Kotlin Fundamentals: 6.2 Coroutines and Room

### ISSUE THREAD

**Issue by GodModeOn** [google-developer-training/android-kotlin-fundamentals-apps#824]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-coroutines-and-room#5

**Describe the problem**
Project builds, but cannot start debugging when SleepDatabaseDao methods have suspend prefix (as described in the lesson)

```
TrackMySleepQuality-Starter/app/build/tmp/kapt3/stubs/debug/com/example/android/trackmysleepquality/database/SleepDatabaseDao.java:11: error: Not sure how to handle insert method's return type.
    public abstract java.lang.Object insert(@org.jetbrains.annotations.NotNull()
```

**In which lesson and step of the codelab can this issue be found?**
[Android Kotlin Fundamentals: 6.2 Coroutines and Room](https://developer.android.com/codelabs/kotlin-android-training-coroutines-and-room)
[6. Task: Collect and display the data](https://developer.android.com/codelabs/kotlin-android-training-coroutines-and-room#5)

**How to reproduce?**
Add suspend prefix to SleepDatabaseDao methids (inser, update, ... ) as described in the lesson and try not just build, but start debug app in the Android Emulator with API 31 + play

**Versions**
1. What version of Android Studio are you using? - 
Android Studio Chipmunk | 2021.2.1 Patch 1
2. What API level are you targeting?
compileSdkVersion 32
minSdkVersion 19
targetSdkVersion 32

**Additional information**

```
kotlin_version = '1.7.10'
archLifecycleVersion = '1.1.1'
room_version = '2.4.2'
coroutine_version = '1.6.3'
gradleVersion = '7.2.1'
navigationVersion = '1.0.0'
dataBindingCompilerVersion = gradleVersion // Always need to be the same.
nav_version = "2.3.0"
```

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // Support libraries
    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'androidx.fragment:fragment-ktx:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Android KTX
    implementation 'androidx.core:core-ktx:1.8.0'

    // Room and Lifecycle dependencies
    implementation "androidx.room:room-runtime:$room_version"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.0'

    // Kotlin Extensions and Coroutines support for Room
    implementation "androidx.room:room-ktx:$room_version"

    // Coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutine_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutine_version"

    // Navigation
//    implementation "android.arch.navigation:navigation-fragment-ktx:$navigationVersion"
//    implementation "androidx.navigation:navigation-ui-ktx:$navigationVersion"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    // Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
```

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
