### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by trhme** [google-developer-training/android-kotlin-fundamentals-apps#825]
[Android Kotlin Fundamentals: 6.2 Coroutines and Room](https://developer.android.com/codelabs/kotlin-android-training-coroutines-and-room)

Date math is wrong in calculating sleep duration
A clear and concise description of what the problem is.

[6. Task: Collect and display the data](https://developer.android.com/codelabs/kotlin-android-training-coroutines-and-room#5)
- Step 4: Display the data
    - Use the formatNights() function from Util.kt.

Duration is calculated with:
```
                // Hours
                append("\t ${it.endTimeMilli.minus(it.startTimeMilli) / 1000 / 60 / 60}:")
                // Minutes
                append("${it.endTimeMilli.minus(it.startTimeMilli) / 1000 / 60}:")
                // Seconds
                append("${it.endTimeMilli.minus(it.startTimeMilli) / 1000}<br><br>")
```

But it should be more like this:
```
                // Hours
                val hour = it.endTimeMilli.minus(it.startTimeMilli) / 1000 / 60 / 60
                append("\t ${hour}:")
                // Minutes
                val mins = it.endTimeMilli.minus(it.startTimeMilli).minus(hour * 3600000) / 1000 / 60
                append("${mins}:")
                // Seconds
                val secs = it.endTimeMilli.minus(it.startTimeMilli)
                    .minus(hour * 3600000).minus(mins * 60000) / 1000
                append("${secs}<br><br>")
```

**Versions**
1. Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.7
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (212-1.7.10-release-333-AS5457.46)

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
