### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Yuga-Git** [google-developer-training/android-kotlin-fundamentals-apps#826]
**Name of the Codelab or Codelab URL**

Explore the lifecycle method and add basic logging

**Describe the problem**
Not able to clone the 
[DessertClicker starter app]  (https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/tree/master/DessertClicker-Starter) 
Please need help

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
