### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by GrecoJava** [google-developer-training/android-kotlin-fundamentals-apps#827]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-add-navigation#6

**Describe the problem**
Task 7, Step 1, item #4 - screenshot is not showing what the text instructs the user to select.  The text guides the user to "set popUpTo to gameFragment"  while the screenshot shows it is set to gameWonFragment.

**In which lesson and step of the codelab can this issue be found?**
Task 7, Step 1, item #4

**How to reproduce?**
Read the code lab lesson

**Versions**
1. What version of Android Studio are you using? 
Android Studio Electric Eel | 2022.1.1 Canary 9
Build #AI-221.5921.22.2211.8881706, built on July 28, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 20
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    String Manipulation (9.5.0)
    Statistic (4.1.10)

3. What API level are you targeting? 30

**Additional information**
n/a

**codelab:** android-kotlin-fundamentals

![image](https://user-images.githubusercontent.com/5533939/183811872-d7cfb1b6-8af8-4f97-9ac6-1e0350f420ca.png)

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
