### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Katabatiko** [google-developer-training/android-kotlin-fundamentals-apps#832]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-work-manager?hl=es-419#7

**Describe the problem**
For use CoroutineWorker it is necesary implement androidx.work:work-runtime-ktx:2.7.1 because  android.arck.work:work-runtime-ktx:1.0.1 not knowns it

**In which lesson and step of the codelab can this issue be found?**
At lesson 9, concept WorkManager, task 6

**How to reproduce?**
When you want use CoroutineWorker as parent class of RefreshDataWorker class

**Versions**
1. What version of Android Studio are you using?
Chipmunk 2021.2.1 Patch 1
2. What API level are you targeting? 30

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
