### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by TeeMans** [google-developer-training/android-kotlin-fundamentals-apps#833]
![image](https://user-images.githubusercontent.com/108068568/189533280-91db98dd-7f7c-4c31-8085-85627a3514bc.png)
Hi I cant download the github code. See screenshot

**Comment by SamiKassoum** [comment]
me too, 
have you find any solution ?

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
