### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by SamiKassoum** [google-developer-training/android-kotlin-fundamentals-apps#836]
Hi,
I think there is a gab between Lesson 4 and 5
in 5 its is written at the beginning the folowing : - 
 "Task: Create a repository
In this task, you'll create a repository to manage the offline cache, which you implemented in the previous task"
but in the previous tast "4" we have not implemented the offline cache !
is there any explanation please , thanks in advance

**Comment by McGregorWiloh** [comment]
> Hi, I think there is a gab between Lesson 4 and 5 in 5 its is written at the beginning the folowing : - "Task: Create a repository In this task, you'll create a repository to manage the offline cache, which you implemented in the previous task" but in the previous tast "4" we have not implemented the offline cache ! is there any explanation please , thanks in advance

I encountered the same problem too

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
