### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Praxys2022** [google-developer-training/android-kotlin-fundamentals-apps#838]
**Name of the Codelab or Codelab URL**
[Android Kotlin Fundamentals: WorkManager](https://developer.android.com/codelabs/kotlin-android-training-work-manager?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fkotlin-fundamentals-nine%23codelab-%2Fcodelabs%2Fkotlin-android-training-work-manager)

**Describe the problem**
A clear and concise description of what the problem is.
      > Failed to list versions for androidx.room:room-common.
         > Unable to load Maven meta-data from https://kotlin.bintray.com/kotlinx/androidx/room/room-common/maven-metadata.xml.
            > Could not get resource 'https://kotlin.bintray.com/kotlinx/androidx/room/room-common/maven-metadata.xml'.
               > Could not GET 'https://kotlin.bintray.com/kotlinx/androidx/room/room-common/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?
Compile project  looks like last update 2 years ago
**Versions**
1. What version of Android Studio are you using? Dolphin
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
