### ISSUE TITLE
me too,

### ISSUE THREAD

**Issue by TeeMans** [google-developer-training/android-kotlin-fundamentals-apps#839]
[
_Originally posted by @SamiKassoum in https://github.com/google-developer-training/android-kotlin-fundamentals-apps/issues/833#issuecomment-1253764775_
      ]
Hi Sami 
Click on below link. You will download all the projects includin the one you are looking for.
(https://github.com/google-developer-training/android-kotlin-fundamentals-apps)

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
