### ISSUE TITLE
Android Kotlin Fundamentals codelab: Repository Pattern

### ISSUE THREAD

**Issue by McGregorWiloh** [google-developer-training/android-kotlin-fundamentals-apps#843]
Code to delete

private val _playlist = MutableLiveData<List<Video>>()
...
val playlist: LiveData<List<Video>>
   get() = _playlist

after deleting the above code in Repository Pattern codelab the function 'refreshDataFromRepository()' still references the variable 'playlist'

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
