### ISSUE TITLE
Android Kotlin Fundamentals codelab: Repository pattern

### ISSUE THREAD

**Issue by kemicky** [google-developer-training/android-kotlin-fundamentals-apps#844]
The code lab starts project has no download link and if the entire starter project is downloaded I can't run selected project as shown in the code labs instructions
 Please kindly explain and clarify which step is missing.
Here Is a screenshots:
- the GitHub starter repository has no clone link , I have to download the entire starter folder

![Screenshot 2022-11-21 at 02 00 12](https://user-images.githubusercontent.com/57273086/202933873-66a7a883-f2d0-45ec-bd71-d170fb7f953d.png)

- After downloading the entire folder can't still run the app to complete the projects as instructed in the code lab

![Screenshot 2022-11-21 at 01 58 57](https://user-images.githubusercontent.com/57273086/202933883-59707cc2-34d3-40bb-be57-0dbbb753c92b.png)

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
