### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by SergeiPavlitz** [google-developer-training/android-kotlin-fundamentals-apps#846]
**Name of the Codelab or Codelab URL**
[12. Task: Add click handlers to the buttons](https://developer.android.com/codelabs/kotlin-android-training-constraint-layout#11)

**Describe the problem**
There is a mistake in the 4 code snippet. (makeColored function)
>>R.id.red_button -> box_three_text.setBackgroundResource(R.color.my_red)
"box_three_text" is highlighted by red in Adroid studio, because it is unknown variable. 

**In which lesson and step of the codelab **
(https://developer.android.com/codelabs/kotlin-android-training-constraint-layout#11)
[Android Kotlin Fundamentals: 02.3 ConstraintLayout using the Layout Editor](https://developer.android.com/codelabs/kotlin-android-training-constraint-layout)

**Describe the problem**
There is a mistake in the 4 can this issue be found?**
Lesson 02.3+ step 4.

**How to reproduce?**

**Versions**
1. What version of Android Studio are you using? 
Android Studio Dolphin | 2021.3.1 Patch 1 
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

2. What API level are you targeting?
minSdk 21
targetSdk 32

**Additional information**
To fix it, I changed the line to this one:
R.id.red_button -> findViewById<TextView>(R.id.box_three_text).setBackgroundResource(R.color.my_red)

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
