### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by SergeiPavlitz** [google-developer-training/android-kotlin-fundamentals-apps#847]
**Name of the Codelab or Codelab URL**
[Task: Add navigation](https://developer.android.com/codelabs/kotlin-android-training-quality-and-states#2)

**Describe the problem**
Unresolved reference: SleepTrackerFragmentDirections

**In which lesson and step of the codelab can this issue be found?**
Lesson number 3, step number 2.6.

**How to reproduce?**
just insert code snipet in the project.
I used project from previous lessons and also caught the same problem in the proejct from the github

**Versions**
1. What version of Android Studio are you using?
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
