### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Antonioescp** [google-developer-training/android-kotlin-fundamentals-apps#848]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-lifecycles-logging#8

**Describe the problem**
the last step is missing the go to next codelab button

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals: Lifecycles and logging
step 9

**How to reproduce?**
What are the exact steps to reproduce the problem?
go to step 9

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
