### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by sgkim99** [google-developer-training/android-kotlin-fundamentals-apps#849]
**Name of the Codelab or Codelab URL**

[Android Kotlin Fundamentals: LinearLayout using the Layout Editor](https://developer.android.com/codelabs/kotlin-android-training-linear-layout)

**Describe the problem**
In this page, when I click the "Add user interactivity" button, this page( https://developer.android.com/codelabs/kotlin-android-training-interactivity#10 ) appears, which looks OK, but "11. Learn more " section is displayed, NOT the first section "1. Introduction".
I found that all other page links for NEXT button(or NEXT codelab) work like this.

In short, page navigation at the end of each chapter DOES NOT work correctly.

Thank you! 

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.villains.intelij.plugin.newoceantheme (1.2.0)
    com.markskelton.one-dark-theme (5.7.1)
    com.ADMARIl.halcyon-jetbrains (2.2.0)
    atom-one (1.5.1)
    Rider UI Theme Pack (0.10.1)
    com.jetbrains.kmm (0.5.1(213)-60)

3. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
