### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by FilipeD** [google-developer-training/android-kotlin-fundamentals-apps#852]
**Name of the Codelab or Codelab URL**
https://github.com/google-developer-training/android-kotlin-fundamentals-apps/issues/new?assignees=&labels=&template=android-kotlin-fundamentals.md&title=Android+Kotlin+Fundamentals+codelab%3A+

**Describe the problem**
No androidx artifacts option while using Electric Eel 2022.1.1 studio version with basic activity template

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
[App overview](https://developer.android.com/codelabs/kotlin-android-training-available-resources#1)

[3. Task: Use project templates](https://developer.android.com/codelabs/kotlin-android-training-available-resources#2)
**How to reproduce?**
What are the exact steps to reproduce the problem?
This ain't a problem... This is a lack of documentation maintenance....

**Versions**
1. What version of Android Studio are you using?
 Electric Eel 2022.1.1

3. What API level are you targeting?
28. 
  
**Additional information**
DO UPDATE THE LESSONS CONTENT so people stop wasting time searching the internet only to find ANDROIDX IS USED BY DEFAULT INSTEAD OF V7 SUPPORT 28.X.X.

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
