### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by MaxencePaulin** [google-developer-training/android-kotlin-fundamentals-apps#854]
**Name of the Codelab or Codelab URL**

**Describe the problem**
Error at one image
**In which lesson and step of the codelab can this issue be found?**
Lesson 6 + Codelab 2, page 7, step 1, point 4

**How to reproduce?**
Just read and see, it told "set popUpTo to gameFragment" but the screen display popUpTo to gameWonFragment

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
