### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by xieeryihe** [google-developer-training/android-kotlin-fundamentals-apps#855]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/kotlin-android-training-add-navigation#9

**Describe the problem**
When I finished the last task of this codelab, I couldn't open the navigation drawer by swiping from the left edge.
I download the solution code and test, but it still doesn't work.
Is this due to a version issue?

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals:03.2 Define navigation paths.
Task: Add the navigation drawer.  Step 4: Display the navigation drawer

**Versions**
1. What version of Android Studio are you using?
Android Studio Electric Eel | 2022.1.1
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
