### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by xvyang-z** [google-developer-training/android-kotlin-fundamentals-apps#862]
link: https://developer.android.com/codelabs/kotlin-android-training-add-navigation#6

![image](https://user-images.githubusercontent.com/83717933/230008423-9483b9c5-daaa-48c3-8846-6101fb57e753.png)

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.

For updated content on user interactivity, please visit [Android Basics with Compose Unit 2 Pathway 2: Add a button to an app](https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-2).
