### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by WANZILA** [google-developer-training/android-kotlin-fundamentals-apps#863]
Unable to download RepositoryPattern-Starter as in the instructions

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.

For updated content on user interactivity, please visit [Android Basics with Compose Unit 2 Pathway 2: Add a button to an app](https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-2).
