### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by sdadasdasdwa** [google-developer-training/android-kotlin-fundamentals-apps#864]
**TrackMySleepQuality**

In this codelab, when I finish working on the room database, once I add the suspend method to the Dao layer, It will report an error like this:

 Query method parameters should either be a type that can be converted into a database column or a List / Array that contains such type. You can consider adding a Type Adapter for this.
    kotlin.coroutines.Continuation<? super com.example.trackmysleepquality.database.SleepNight> continuation);

I guess the reason of error is the conflict between two dependencies like room-kapt and coroutine.

**some of my dependencies are as follows:**
// Room and Lifecycle dependencies
    def room_version = '2.3.0'
    implementation "androidx.room:room-runtime:$room_version"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"

// Coroutines
    def coroutine_version = '1.5.10'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutine_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutine_version"

I tried for a long time and still failed.

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.

For updated content on user interactivity, please visit [Android Basics with Compose Unit 2 Pathway 2: Add a button to an app](https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-2).
