### ISSUE TITLE
8.1 Getting data from the internet - response.body()?.size not resolved

### ISSUE THREAD

**Issue by Tonnie-Dev** [google-developer-training/android-kotlin-fundamentals-apps#95]
**Describe the problem**
response.body()?.size not resolved

**In which lesson and step of the codelab can this issue be found?**
08.1: Getting data from the internet, Parse the JSON response with Moshi, Step 3

**How to reproduce?**
when you call response.body()?.size to get the a count on MarsProperties you encounter the error.
Have tried cleaning and rebuiding the code to no avail.

**Versions**
1. What version of Android Studio are you using? I'm running AS 3.6.2
2. What API level are you targeting? I'm targeting API 29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by TheCodingArcher** [comment]
Same thing happening to me @Fanadezz 
```
java.lang.IllegalArgumentException: Unable to create converter for java.util.List<a.b.c.marsrealestate.network.MarsProperty>
        for method MarsApiService.getProperties
```

I tried everything, including the original files and dependencies but yet no luck. Please share your solution if you find anything.
