### ISSUE TITLE
Android Kotlin Fundamentals codelab: 06.2 

### ISSUE THREAD

**Issue by ipshitaRB** [google-developer-training/android-kotlin-fundamentals-apps#98]
**Describe the problem**
ViewModelProviders.of() is deprecated

**In which lesson and step of the codelab can this issue be found?**
Lesson number 06.2 Task 4  step number 3 Point number 4.

**How to reproduce?**
Type the following code after following the earlier parts of the codelab
val sleepTrackerViewModel =
       ViewModelProviders.of(
               this, viewModelFactory).get(SleepTrackerViewModel::class.java) . 

**Versions**
1. What version of Android Studio are you using? - 3.6.2
2. What API level are you targeting? - 28

**Additional information**
Please update the latest substitute code for this segment. 

**codelab:** android-kotlin-fundamentals

**Comment by Fanadezz** [comment]
hi @ipshitaRB you can use ViewModelProvider(this, viewModelFactory).get()

hope this helps, cheers.

**Comment by flplatet** [comment]
Duplicate of #33
